<template>
<admin-layout><main class="ref-admin">
  <h1>{{ $t('邀请与返佣中心') }}</h1>
  <p>{{ $t('交易所与 UMI 使用独立邀请关系和奖励规则，共享登录身份。') }}</p>
  <form class="ref-controls" @submit.prevent="filter"><label>UID <input v-model="uid" type="number" min="1" /></label><button>{{ $t('查询') }}</button><a :href="route('admin.referral-center')">{{ $t('重置') }}</a></form>
  <nav class="ref-tabs"><button :aria-pressed="tab==='exchange'" @click="tab='exchange'">{{ $t('交易所返佣') }}</button><button :aria-pressed="tab==='umi'" @click="tab='umi'">{{ $t('UMI 邀请') }}</button></nav>
  <template v-if="tab==='exchange'">
    <section><h2>{{ $t('规则版本') }} · {{ rules.version }}</h2><p>{{ $t('各级按交易手续费分成；受益人 VIP 0/1 可得第 1 级，VIP 2–8 对应最高层级。历史记录不重算。') }}</p><div class="ref-rates"><span v-for="(rate,level) in rules.rates" :key="level">{{ $t('层级') }} {{ level }} · <b>{{ rate }}%</b></span></div><p>{{ $t('返佣任务最近运行') }}: {{ heartbeat ? heartbeat.finished_at : $t('暂无记录') }}</p></section>
    <section><h2>{{ $t('返佣状态') }}</h2><p>{{ $t('按币种和真实／模拟账户分别统计。旧记录缺少来源证明时待核对，不自动补发。') }}</p><div class="ref-table"><table><thead><tr><th>{{ $t('Currency') }}</th><th>{{ $t('账户类型') }}</th><th>{{ $t('状态') }}</th><th>{{ $t('数量') }}</th><th>{{ $t('Amount') }}</th></tr></thead><tbody><tr v-for="(s,i) in summary" :key="i"><td>{{s.symbol}}</td><td>{{domain(s.balance_domain)}}</td><td>{{status(s.credit_status)}}</td><td>{{s.count}}</td><td>{{number(s.amount)}}</td></tr></tbody></table></div></section>
    <section><h2>{{ $t('交易所邀请关系') }}</h2><p>{{ $t('最近 100 条；可用 UID 查询。') }}</p><div class="ref-table"><table><thead><tr><th>UID</th><th>{{ $t('Email') }}</th><th>{{ $t('邀请码') }}</th><th>{{ $t('直属上级') }}</th><th>VIP</th><th>{{ $t('账户类型') }}</th></tr></thead><tbody><tr v-for="u in exchange" :key="u.id"><td>{{u.id}}</td><td>{{u.email}}</td><td>{{u.referral_code}}</td><td>{{u.parent_code || '—'}}</td><td>{{u.vip}}</td><td>{{domain((u.is_xn||u.is_xm)?'virtual':'real')}}</td></tr></tbody></table></div></section>
    <section><h2>{{ $t('返佣明细与凭证') }}</h2><div class="ref-table"><table><thead><tr><th>ID / {{ $t('Date') }}</th><th>{{ $t('来源 / 受益人') }}</th><th>{{ $t('层级') }}</th><th>{{ $t('手续费 / 返佣') }}</th><th>{{ $t('状态') }}</th><th>{{ $t('入账凭证') }}</th></tr></thead><tbody><tr v-for="r in rows.data" :key="r.id"><td>#{{r.id}}<small>{{r.created_at}}</small></td><td>{{business(r.business)}}<small>{{r.source_user_id || '—'}} → {{r.user_id}}</small></td><td>{{r.reward_level || '—'}}</td><td>{{number(r.fee)}} / {{number(r.amount)}} {{r.symbol}}<small>{{domain(r.balance_domain)}}</small></td><td>{{status(r.credit_status)}}<small>{{reason(r.last_error)}}</small></td><td v-if="r.wallet_id">#{{r.wallet_id}}<small>{{number(r.balance_before)}} → {{number(r.balance_after)}}</small></td><td v-else>—</td></tr></tbody></table></div><div class="ref-pages"><a v-if="rows.prev_page_url" :href="rows.prev_page_url">{{ $t('上一页') }}</a><span>{{rows.current_page}} / {{rows.last_page}}</span><a v-if="rows.next_page_url" :href="rows.next_page_url">{{ $t('下一页') }}</a></div></section>
  </template>
  <template v-else><section><h2>{{ $t('UMI 专属邀请码') }}</h2><p>{{ $t('新用户须用有效上级的 UMI 专属邀请码激活。原账户关系和奖励机制保持不变；交易所邀请码不能代替。') }}</p><a :href="route('admin.umi.business')">{{ $t('UMI Business Management') }} →</a><p>{{ $t('最近 100 条；可用 UID 查询。') }}</p><div class="ref-table"><table><thead><tr><th>UMI ID / UID</th><th>{{ $t('UMI 专属邀请码') }}</th><th>{{ $t('直属上级') }}</th><th>{{ $t('原 UID') }}</th><th>{{ $t('邀请资格') }}</th></tr></thead><tbody><tr v-for="a in umi" :key="a.id"><td>{{a.id}} / {{a.user_id || '—'}}</td><td>{{a.code}}</td><td>{{a.parent_code || a.legacy_parent_id || '—'}}</td><td>{{a.legacy_id || '—'}}</td><td>{{a.can_invite?$t('可邀请'):$t('待激活或已停用')}}</td></tr></tbody></table></div></section></template>
</main></admin-layout>
</template>
<script>
import AdminLayout from '@/Layouts/AdminLayout';
export default {components:{AdminLayout},props:{rules:Object,rows:Object,summary:Array,exchange:Array,umi:Array,filters:Object,heartbeat:Object},
  data(){return {tab:'exchange',uid:this.filters.user || ''};},
  methods:{filter(){window.location.href=this.route('admin.referral-center')+(this.uid?'?user='+encodeURIComponent(this.uid):'');},number(v){return v==null?'—':String(v).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,'');},
    domain(v){return this.$t({real:'真实账户',virtual:'模拟账户'}[v] || '历史来源待核对');},
    business(v){return this.$t({spot:'现货',futures_entry:'合约开仓',futures_exit:'合约平仓'}[v] || '历史记录');},
    status(v){return this.$t({pending:'待入账',failed:'失败待重试',review:'待核对',credited:'已到账',legacy_credited:'历史已入账'}[v] || '待核对');},
    reason(v){return v?this.$t({legacy_source_review:'历史来源待核对',recipient_unavailable:'受益账户不可用',recipient_domain_changed:'账户类型已变更',wallet_missing:'钱包不存在',source_mismatch:'来源记录不一致',domain_mismatch:'账户类型不一致',credit_error:'入账失败，请核对日志'}[v] || '待核对'):'';}
  }};
</script>
<style scoped>
.ref-admin{max-width:100%;color:var(--ui-text,#18202a);padding:12px}.ref-admin h1{font-size:26px;font-weight:750;margin-bottom:12px}.ref-admin h2{font-size:19px;font-weight:700}.ref-admin p{line-height:1.65;margin:12px 0;color:var(--ui-muted,#697483)}.ref-admin section{background:var(--ui-surface,#fff);border:1px solid var(--ui-line,#c7a957);border-radius:16px;padding:22px;margin:18px 0}.ref-admin a{color:var(--ui-accent-text,#8a681b)}.ref-controls,.ref-tabs,.ref-rates,.ref-pages{display:flex;gap:12px;align-items:center;flex-wrap:wrap}.ref-controls input{width:150px;border:1px solid var(--ui-line,#c7a957);border-radius:8px;background:var(--ui-surface,#fff);padding:8px;color:inherit}.ref-admin button,.ref-rates span{padding:10px 14px;border:1px solid var(--ui-line,#c7a957);border-radius:10px;background:var(--ui-surface,#fff)}.ref-tabs{margin-top:20px}.ref-tabs button[aria-pressed=true]{background:#f6d145;color:#18202a}.ref-table{max-width:100%;overflow:auto;margin-top:16px}.ref-table table{width:100%;text-align:left;white-space:nowrap}.ref-table td,.ref-table th{padding:13px 14px;border-bottom:1px solid var(--ui-line,#c7a957)}.ref-table small{display:block;color:var(--ui-muted,#697483);margin-top:4px}.ref-pages{justify-content:center;margin-top:18px}@media(max-width:600px){.ref-admin{padding:0}.ref-admin section{padding:14px}.ref-admin h1{font-size:23px}}
</style>
