<template><app-layout><Head :title="$t(&quot;原 UMI 用户激活 · Deepro&quot;)"/><main class="umi-account"><section class="umi-activation-card"><span class="umi-eyebrow">WELCOME BACK TO UMI</span><h1>{{ $t("原 UMI 用户激活") }}</h1><p>{{ $t("验证原账户身份，设置新的登录密码。您的原有关系、等级和历史资料将继续保留。") }}</p><ol class="umi-steps"><li :class="{active:!challenge}">{{ $t("01 确认账户") }}</li><li :class="{active:challenge&&!done}">{{ $t("02 验证与设密") }}</li><li :class="{active:done}">{{ $t("03 返回登录") }}</li></ol>
<form v-if="!challenge" @submit.prevent="send"><label for="umi-identifier">{{ $t("原邮箱、原 UID 或原账号标识") }}</label><input id="umi-identifier" v-model="identifier" autocomplete="username" required maxlength="255" :placeholder="$t(&quot;请输入原账户信息&quot;)"/><button class="umi-action" :disabled="busy || cooldown > 0">{{busy?$t("正在提交…"):(cooldown>0?cooldown+$t(" 秒后可重新发送"):$t("获取激活验证码"))}}</button></form>
<form v-else-if="!done" @submit.prevent="activate"><p class="umi-history-note">{{ $t("若账户已核定可用邮箱，验证码将发送至该邮箱。未收到时请联系账户支持，不要重新注册或更换推荐人。") }}</p><label for="umi-code">{{ $t("邮箱验证码") }}</label><input id="umi-code" v-model="code" autocomplete="one-time-code" inputmode="numeric" pattern="[0-9]{8}" maxlength="8" required/><label for="umi-password">{{ $t("设置新密码") }}</label><input id="umi-password" v-model="password" type="password" autocomplete="new-password" minlength="12" maxlength="72" required :placeholder="$t(&quot;至少 12 位&quot;)"/><label for="umi-confirm">{{ $t("再次输入新密码") }}</label><input id="umi-confirm" v-model="confirmation" type="password" autocomplete="new-password" required/><button class="umi-action" :disabled="busy">{{busy?$t("正在验证…"):$t("验证并设置密码")}}</button><p class="umi-history-note">{{ $t("验证码 10 分钟内有效。请查看收件箱及垃圾邮件，重发后请使用最新验证码。") }}</p><button type="button" class="umi-text-button" :disabled="busy || cooldown > 0" @click="send">{{cooldown > 0 ? cooldown + $t(" 秒后可重新发送") : $t("重新发送验证码")}}</button><button type="button" class="umi-text-button" :disabled="busy" @click="restart">{{ $t("更换原账号信息") }}</button></form>
<div v-else class="umi-success"><h2>{{ $t("密码设置成功") }}</h2><p>{{ $t("请使用已验证邮箱和刚设置的密码登录，并完成邮箱验证码验证。原 UMI UID 和账户关系保持不变。") }}</p><a :href="route('login')" class="umi-action">{{ $t("前往登录") }}</a></div><p v-if="error" role="alert" class="umi-error">{{ $t(error) }}</p><div class="umi-activation-help"><strong>{{ $t("原联系方式已失效？") }}</strong><p>{{ $t("请通过账户支持核验原账户归属。仅凭用户名无法设置密码。") }}</p><button class="umi-text-button" @click="recoveryOpen=!recoveryOpen">{{ $t("申请人工核验 →") }}</button><form v-if="recoveryOpen" @submit.prevent="recover"><label for="recovery-account">{{ $t("原账号信息") }}</label><input id="recovery-account" v-model="recovery.identifier" required maxlength="255"/><label for="recovery-email">{{ $t("可联系邮箱") }}</label><input id="recovery-email" v-model="recovery.reply_email" type="email" required/><label for="recovery-evidence">{{ $t("可核对的历史记录说明") }}</label><textarea id="recovery-evidence" v-model="recovery.evidence" minlength="20" maxlength="2000" rows="4" required :placeholder="$t(&quot;请勿填写密码、验证码或私钥。&quot;)"/><button class="umi-action" :disabled="busy">{{ $t("提交账户核验申请") }}</button></form><p v-if="recoveryReference" role="status">{{ $t("申请编号：") }}{{recoveryReference}}{{ $t("。请保存编号，核验通过前不会变更账户。") }}</p></div></section></main></app-layout></template>
<script>
import UmiLocale from '@/Functions/UmiLocale';
import { legacyText } from '@/Functions/LegacyTranslation';

import AppLayout from '@/Layouts/AppLayout';import './umi-account.scss';
export default {mixins:[UmiLocale],components:{AppLayout},data:()=>({identifier:'',challenge:'',code:'',password:'',confirmation:'',busy:false,cooldown:0,timer:null,error:'',done:false,recoveryOpen:false,recoveryReference:'',recovery:{identifier:'',reply_email:'',evidence:''}}),beforeDestroy(){clearInterval(this.timer);},methods:{
 startCooldown(){this.cooldown=60;clearInterval(this.timer);this.timer=setInterval(()=>{this.cooldown=Math.max(0,this.cooldown-1);if(!this.cooldown)clearInterval(this.timer);},1000);},
 async recover(){this.busy=true;this.error='';try{const r=await axios.post(this.route('umi.recovery'),this.recovery,{timeout:20000});this.recoveryReference=r.data.reference;this.recoveryOpen=false;}catch(e){this.failure(e);}finally{this.busy=false;}},
 async send(){if(this.busy||this.cooldown>0)return;this.busy=true;this.error='';try {const r=await axios.post(this.route('umi.activate.code'),{identifier:this.identifier},{timeout:20000});this.challenge=r.data.challenge;this.code='';this.startCooldown();}catch(e){this.failure(e);}finally{this.busy=false;}},
 async activate(){this.busy=true;this.error='';try{await axios.post(this.route('umi.activate.complete'),{challenge:this.challenge,code:this.code,password:this.password,password_confirmation:this.confirmation},{timeout:20000});this.done=true;}catch(e){this.failure(e);}finally{this.password='';this.confirmation='';this.busy=false;}},
 restart(){if(this.busy)return;this.challenge='';this.code='';this.password='';this.confirmation='';this.error='';},
 failure(e){const d=e.response&&e.response.data;this.error=d&&d.errors?Object.values(d.errors).flat()[0]:(e.response&&e.response.status===429?legacyText("操作较频繁，请稍后重试。"):legacyText("暂时无法处理，请稍后重试。"));}
}};
</script>
