<template>
<app-layout><Head :title="$t(&quot;UMI 生态账户 · Deepro&quot;)"/><main class="ub-page">
  <div class="ub-heading"><div><span class="ub-eyebrow">UMI ECOSYSTEM</span><h1>{{ $t("我的 UMI") }}</h1><p>{{ $t("管理额度、收益与团队，让每一笔变动都有迹可循。") }}</p></div><a :href="route('umi.account')">{{ $t("原账户档案 ↗") }}</a></div>
  <div class="ub-notice"><strong>{{state.funded_live?$t("UMI 生态账户"):state.read_only?$t("云端核验"):$t("本地验收")}}</strong><span>{{state.funded_live?$t("已结算至"):$t("业务日期")}} {{state.date}} · {{state.funded_live?$t("可与交易所资金账户划转，历史档案独立保留。"):$t("此处资金与原账户、交易所钱包独立，不构成链上充提。")}}</span><b v-if="state.paused">{{ $t("业务暂停中") }}</b></div>
  <div v-if="state.read_only" class="ub-notice"><strong>{{ $t("资金接续待验收") }}</strong><span>{{ $t("完整业务页面已发布；原用户资料与关系可核查。UMI 真实入金及历史权益接续尚未完成，因此认购、收益发放、兑换和解押暂不执行。") }}</span></div>
  <legacy-binding v-if="!portfolio&&!legacy"/><section v-if="!portfolio&&legacy" class="ub-card"><h2>{{ $t("原账户") }} {{legacy.legacy_id}}</h2><p>{{ $t("账户已绑定，历史权益正在核对接续。可在原账户档案查看已取得的资料。") }}</p></section><section v-if="!portfolio&&!legacy" class="ub-card ub-onboard"><h2>{{ $t("开通 UMI 生态账户") }}</h2><p>{{ $t("邀请关系仅在首次开通时绑定，确认后不能更换。原 UMI 用户请使用原账户档案入口，保留原有关系与权益。") }}</p><form @submit.prevent="submit('enroll')"><fieldset :disabled="busy || state.read_only" class="ub-fieldset"><label>{{ $t("UMI 专属邀请码（必填）") }}<input v-model.trim="parent" :placeholder="$t(&quot;请输入上级的 UMI 专属邀请码&quot;)" maxlength="24" required autocomplete="off" /></label><p>{{ $t("UMI 邀请关系与交易所推荐关系独立；交易所邀请码不能用于激活 UMI。") }}</p><button :disabled="busy || !parent">{{ $t("开通账户") }}</button></fieldset></form></section>
  <template v-if="portfolio"><section v-if="portfolio.opening" class="ub-card"><h2>{{ $t("原账户收益接续") }}</h2><p>{{ $t("原 UID") }} {{portfolio.opening.legacy_id}} {{ $t("· 截止日") }} {{portfolio.opening.cutoff}}</p><p>{{ $t("当前每日释放") }} {{fmt(portfolio.release.daily_amount)}} UMI · {{portfolio.release.status==='active'?$t("正常释放"):portfolio.release.status==='paused'?$t("已暂停"):$t("待核对")}}{{ $t("，以剩余额度为上限。") }}</p></section>
    <section class="ub-hero"><div><span>{{ $t("UMI 总资产") }}</span><strong>{{fmt(portfolio.total_umi)}} <small>UMI</small></strong><p>{{ $t("账户") }} {{portfolio.account.code}} · {{portfolio.account.level ? 'V'+portfolio.account.level : $t("普通会员")}} · VIP {{portfolio.vip_level}}</p><a class="ub-mobile-action" href="#umi-business-actions">{{ $t("账户操作 ↓") }}</a></div><div class="ub-hero-stats"><div><span>{{ $t("可用余额") }}</span><b>{{fmt(portfolio.balances.main)}}</b></div><div><span>{{ $t("剩余收益额度") }}</span><b>{{fmt(portfolio.remaining)}}</b></div><div><span>{{ $t("UMI 宝本金") }}</span><b>{{fmt(portfolio.balances.treasure)}}</b></div></div></section>
    <section v-if="portfolio.opening" class="ub-card"><h2>{{ $t("原 UMI 账户已接续") }}</h2><p>{{ $t("原 UID") }} {{portfolio.opening.legacy_id}} {{ $t("· 截止") }} {{portfolio.opening.cutoff}} · {{portfolio.opening.status==='ready'?$t("从原剩余额度继续计算收益"):$t("部分历史权益待核对，详见原账户资料")}}。</p><p>{{ $t("UMI 为站内记账资产；领取、划转与交易的记录可以在资产明细中核对。") }}</p></section><nav class="ub-tabs" :aria-label="$t(&quot;UMI 账户导航&quot;)"><button v-for="t in tabs" :key="t.id" :class="{selected:tab===t.id}" @click="tab=t.id">{{t.name}}</button></nav>
    <div class="ub-layout"><div class="ub-main">
      <template v-if="tab==='overview'">
        <div class="ub-grid"><article v-for="b in pockets" :key="b.key" class="ub-card ub-metric"><span>{{ $t(b.label) }}</span><strong>{{fmt(portfolio.balances[b.key])}}</strong><small>{{b.key==='usdt'?'USDT':b.key==='points'?$t("积分"):'UMI'}}</small></article></div>
        <section class="ub-card"><h2>{{ $t("收益额度") }}</h2><dl><div><dt>{{ $t("总额度") }}</dt><dd>{{fmt(portfolio.account.quota_total)}} UMI</dd></div><div><dt>{{ $t("累计已使用") }}</dt><dd>{{fmt(portfolio.account.quota_used)}} UMI</dd></div><div><dt>{{ $t("剩余额度") }}</dt><dd>{{fmt(portfolio.remaining)}} UMI</dd></div></dl><p>{{ $t("线性释放、直推、团队与宝利息共用额度。划转或提取收益不会恢复已消耗的额度。") }}</p></section>
      </template>
      <section v-if="tab==='orders'" class="ub-card"><h2>{{ $t("认购与释放计划") }}</h2><div v-if="portfolio.opening" class="ub-notice"><strong>{{ $t("原账户释放接续") }}</strong><span>{{ $t("快照日释放") }} {{fmt(portfolio.opening.daily_release)}} {{ $t("UMI · 自 2026-09-17 起按剩余额度结算；原认购记录保留在历史档案。") }}</span></div><p>{{ $t("每笔计划保存认购时的价格、倍数和日比例；新配置不会覆盖旧单。") }}</p><div class="ub-table"><table><thead><tr><th>{{ $t("计划 / 来源") }}</th><th>{{ $t("数量 / 价值") }}</th><th>{{ $t("额度 / 已释放") }}</th><th>{{ $t("日释放") }}</th><th>{{ $t("起算 / 状态") }}</th></tr></thead><tbody><tr v-for="p in portfolio.plans" :key="p.id"><td>#{{p.id}}<small>{{p.burn_type===3?$t("赠送"):$t("认购")}}</small></td><td>{{fmt(p.amount)}} UMI<small>{{fmt(p.value_usdt)}} USDT</small></td><td>{{fmt(p.quota)}}<small>{{ $t("已释放") }} {{fmt(p.released)}}</small></td><td>{{fmt(p.release?.daily_amount??p.daily_amount)}}<small>{{percent(p.release?.daily_rate??p.daily_rate)}} {{ $t("/ 日") }}</small></td><td>{{p.starts_on}}<small>{{statusName(p.status==='completed'?'completed':p.release?.status??p.status)}}</small></td></tr></tbody></table></div><p v-if="!portfolio.plans.length" class="ub-empty">{{ $t("暂无新增认购计划") }}</p></section>
      <template v-if="tab==='treasure'"><section class="ub-card"><span class="ub-eyebrow">UMI TREASURE</span><h2>{{ $t("UMI 宝") }}</h2><div class="ub-large">{{fmt(portfolio.balances.treasure)}} <small>UMI</small></div><dl><div><dt>{{ $t("日计息比例") }}</dt><dd>{{percent(state.rules.treasure_daily_rate)}}</dd></div><div><dt>{{ $t("提取手续费") }}</dt><dd>{{percent(state.rules.treasure_fee)}} · {{state.rules.treasure_fee_source==='reserve'?$t("储备金扣除"):$t("提取额内扣除")}}</dd></div></dl><p>{{ $t("先按上一业务日结余计息，再将当日线性和团队收益自动存入。直推收益单独保留，全部收益仍受剩余额度约束。") }}</p></section><section class="ub-card"><h2>{{ $t("储备金与积分") }}</h2><dl><div><dt>{{ $t("储备金") }}</dt><dd>{{fmt(portfolio.balances.reserve)}} UMI</dd></div><div><dt>{{ $t("累计内部积分") }}</dt><dd>{{fmt(portfolio.balances.points)}}</dd></div></dl><p>{{ $t("选择储备金扣费时，储备消费按 1:1 记录积分。积分暂不支持股票兑换，也不代表链上销毁凭证。") }}</p></section></template>
      <template v-if="tab==='team'"><section class="ub-card"><h2>{{ $t("我的团队") }}</h2><dl><div><dt>{{ $t("UMI 专属邀请码") }}</dt><dd>{{portfolio.account.code}}</dd></div><div><dt>{{ $t("直属上级") }}</dt><dd>{{portfolio.parent || (portfolio.account.legacy_parent_id?$t("原 UID ")+portfolio.account.legacy_parent_id+$t("（资料待接续）"):$t("无"))}}</dd></div><div><dt>{{ $t("直属 / 团队人数") }}</dt><dd>{{portfolio.direct}} / {{portfolio.team.length}}</dd></div><div><dt>{{ $t("个人 / 团队业绩") }}</dt><dd>{{fmt(portfolio.account.personal)}} / {{fmt(portfolio.account.team)}} USDT</dd></div><div><dt>{{ $t("小区业绩") }}</dt><dd>{{fmt(portfolio.account.small_area)}} USDT</dd></div></dl><p>{{ $t("分享此 UMI 专属邀请码给新用户，在开通 UMI 生态账户时填写。交易所推荐关系不会因此改变。") }}</p><p>{{ $t("小区业绩为所有直属分支业绩之和减去最大分支。团队按有效等级级差计算，直推在下级认购时结算。") }}</p><div class="ub-table"><table><thead><tr><th>{{ $t("账户") }}</th><th>{{ $t("直属上级") }}</th><th>{{ $t("距离") }}</th><th>{{ $t("等级") }}</th><th>{{ $t("个人业绩") }}</th></tr></thead><tbody><tr v-for="m in portfolio.team" :key="m.code"><td>{{m.code}}</td><td>{{m.parent}}</td><td>{{m.depth}} {{ $t("层") }}</td><td>V{{m.level}}</td><td>{{fmt(m.personal)}} USDT</td></tr></tbody></table></div><p v-if="!portfolio.team.length" class="ub-empty">{{ $t("暂无下级成员") }}</p></section></template>
      <template v-if="tab==='vip'"><section class="ub-card"><h2>{{ $t("VIP 质押") }}</h2><div class="ub-large">{{fmt(portfolio.balances.vip)}} <small>UMI · VIP {{portfolio.vip_level}}</small></div><p>{{ $t("当前门槛：") }}{{state.rules.vip_thresholds.join(' / ')}} {{ $t("UMI。VIP 与团队 V 等级分别计算。") }}</p><dl><div><dt>{{ $t("解押等待") }}</dt><dd>{{state.rules.unstake_minutes}} {{ $t("分钟") }}</dd></div><div><dt>{{ $t("解押手续费") }}</dt><dd>{{percent(state.rules.vip_fee)}}</dd></div><div><dt>{{ $t("解押中") }}</dt><dd>{{fmt(portfolio.balances.unstaking)}} UMI</dd></div></dl><p>{{ $t("申请时固定费率和解锁时间，后续配置不会修改已有申请。") }}{{state.funded_live?$t("到期后系统自动处理，手续费按申请时的规则计算。"):$t("当前使用页面顶部的本地业务日期推进到期处理。")}}</p></section><section class="ub-card"><h2>{{ $t("解押记录") }}</h2><div class="ub-table"><table><thead><tr><th>{{ $t("编号") }}</th><th>{{ $t("数量") }}</th><th>{{ $t("原费率") }}</th><th>{{ $t("解锁时间") }}</th><th>{{ $t("状态") }}</th></tr></thead><tbody><tr v-for="u in portfolio.unstakes" :key="u.id"><td>#{{u.id}}</td><td>{{fmt(u.amount)}}</td><td>{{percent(u.fee_rate)}}</td><td>{{u.unlock_at}}</td><td>{{u.completed_at?$t("已到账"):$t("等待解锁")}}</td></tr></tbody></table></div></section></template>
      <template v-if="tab==='ledger'"><section class="ub-card"><h2>{{ $t("收益明细") }}</h2><p>{{ $t("每笔显示应得、实际到账与额度限制，保留规则版本。") }}</p><div class="ub-table"><table><thead><tr><th>{{ $t("日期 / 类型") }}</th><th>{{ $t("基数 × 比例") }}</th><th>{{ $t("应得 / 到账") }}</th><th>{{ $t("说明") }}</th></tr></thead><tbody><tr v-for="r in portfolio.rewards.data" :key="r.id"><td>{{r.business_date}}<small>{{rewardName(r.kind)}}</small></td><td>{{fmt(r.base)}} × {{percent(r.rate)}}</td><td>{{fmt(r.expected)}}<small>{{ $t("到账") }} {{fmt(r.paid)}}</small></td><td>{{reasonName(r.reason)}}<small>{{ $t("规则 #") }}{{r.rule_id}}</small></td></tr></tbody></table></div><p v-if="!portfolio.rewards.total" class="ub-empty">{{ $t("暂无收益") }}</p><div class="ub-pagination"><a v-if="portfolio.rewards.prev_page_url" :href="portfolio.rewards.prev_page_url+'#ledger'">{{ $t("上一页") }}</a><span>{{ $t("共") }} {{portfolio.rewards.total}} {{ $t("条") }}</span><a v-if="portfolio.rewards.next_page_url" :href="portfolio.rewards.next_page_url+'#ledger'">{{ $t("下一页") }}</a></div></section><section class="ub-card"><h2>{{ $t("最近 40 条资产变动") }}</h2><div class="ub-table"><table><thead><tr><th>{{ $t("时间 / 操作") }}</th><th>{{ $t("账户") }}</th><th>{{ $t("变化") }}</th><th>{{ $t("变动后") }}</th></tr></thead><tbody><tr v-for="e in portfolio.entries" :key="e.id"><td>{{e.created_at}}<small>{{e.description}}</small></td><td>{{pocketName(e.bucket)}}</td><td>{{fmt(e.delta)}} {{e.asset}}</td><td>{{fmt(e.balance_after)}}</td></tr></tbody></table></div></section></template>
    </div>
    <aside id="umi-business-actions" class="ub-card ub-action-card"><h2>{{ $t("账户操作") }}</h2><form @submit.prevent="submit(action)"><fieldset :disabled="busy || state.read_only" class="ub-fieldset"><label>{{ $t("业务") }}<themed-select v-model="action"><option v-for="o in actions" :value="o.id" :key="o.id">{{o.name}}</option></themed-select></label><label v-if="['claim','claim_to_wallet'].includes(action)">{{ $t("收益来源") }}<themed-select v-model="pocket"><option value="linear">{{ $t("线性收益") }}</option><option value="team">{{ $t("团队收益") }}</option><option value="referral">{{ $t("直推收益") }}</option><option v-if="action==='claim_to_wallet'" value="treasure">{{ $t("UMI 宝") }}</option></themed-select></label><label v-if="['swap','custody_in','custody_out'].includes(action)">{{ $t("支付资产") }}<themed-select v-model="asset"><option>USDT</option><option>UMI</option></themed-select></label><label v-if="action==='transfer'">{{ $t("收款账户") }}<input v-model.trim="recipient" :placeholder="$t(&quot;UMI 账户编号&quot;)" maxlength="24" required /></label><label>{{ $t("数量 ·") }} {{['swap','custody_in','custody_out'].includes(action)?asset:'UMI'}}<input v-model.trim="amount" inputmode="decimal" placeholder="0.00" maxlength="43" required /></label><p class="ub-action-help">{{actionHelp}}</p><div class="ub-quote" v-if="action==='purchase'||action==='swap'">{{ $t("参考价") }} <b>{{fmt(state.rules.price)}} USDT / UMI</b><small>{{ $t("规则版本 #") }}{{state.rule_id || $t("初始版本")}}</small></div><operation-preview v-if="currentQuote" :quote="currentQuote"/><button :disabled="busy||state.paused||state.read_only">{{busy?$t("处理中…"):currentQuote?$t("确认")+actionLabel:$t("预览费用与到账")}}</button></fieldset></form><a :href="route('umi.account')" class="ub-subtle">{{ $t("查看原 UMI 历史档案 →") }}</a></aside>
    </div>
  </template>
  <p v-if="message" class="ub-feedback" role="status">{{ $t(message) }}</p><p v-if="error" class="ub-error" role="alert">{{ $t(error) }}</p>
  <details class="ub-card ub-assumptions"><summary>{{ $t("规则依据与待核定事项") }}</summary><p v-for="(a,i) in state.rules.assumptions" :key="i">{{ $t(a) }}</p></details>
</main></app-layout>
</template>
<script>
import UmiLocale from '@/Functions/UmiLocale';
import { legacyText } from '@/Functions/LegacyTranslation';

import AppLayout from '@/Layouts/AppLayout';
import axios from 'axios';
import LegacyBinding from './LegacyBinding.vue';
import OperationPreview from './OperationPreview.vue';
import './business.scss';
export default {mixins:[UmiLocale],
  components:{AppLayout,LegacyBinding,OperationPreview},props:{state:Object,portfolio:Object,legacy:Object},
  data(){return{quote:null,quoteHash:'',tab:location.hash==='#ledger'?'ledger':'overview',busy:false,error:'',message:'',parent:'',action:this.portfolio?.opening?'claim_to_wallet':'purchase',amount:'',asset:'USDT',pocket:this.portfolio?.opening?'treasure':'referral',recipient:'',pending:null,noticeTimer:null,tabs:[{id:'overview',name:legacyText("资产总览")},{id:'orders',name:legacyText("认购计划")},{id:'treasure',name:legacyText("UMI 宝")},{id:'team',name:legacyText("团队")},{id:'vip',name:legacyText("VIP 质押")},{id:'ledger',name:legacyText("收支明细")}],pockets:[{key:'main',label:legacyText("可用 UMI")},{key:'usdt',label:legacyText("可用 USDT")},{key:'linear',label:legacyText("线性收益")},{key:'team',label:legacyText("团队收益")},{key:'referral',label:legacyText("直推收益")},{key:'reserve',label:legacyText("储备金")},{key:'vip',label:legacyText("VIP 质押")},{key:'unstaking',label:legacyText("解押中")}],actions:[{id:'claim_to_wallet',name:legacyText("领取并转入资金账户")},...(this.state.funded_live?[{id:'custody_in',name:legacyText("从交易所资金账户转入")},{id:'custody_out',name:legacyText("转回交易所资金账户")}]:[]),{id:'purchase',name:legacyText("认购释放计划")},{id:'claim',name:legacyText("收益划转到可用余额")},{id:'treasure_deposit',name:legacyText("存入 UMI 宝")},{id:'treasure_withdraw',name:legacyText("提取 UMI 宝")},{id:'reserve_deposit',name:legacyText("存入储备金")},{id:'swap',name:legacyText("UMI / USDT 兑换")},{id:'transfer',name:legacyText("站内转账")},{id:'stake',name:legacyText("VIP 质押")},{id:'unstake',name:legacyText("申请解押")}]};},
  computed:{currentQuote(){return this.quoteHash===JSON.stringify(this.operationInput(this.action))?this.quote:null;},actionLabel(){return this.actions.find(a=>a.id===this.action)?.name||legacyText("提交");},actionHelp(){const r=this.state.rules;return {claim_to_wallet:legacyText("按所选账户规则扣费，净额转入交易所资金账户；不足 18 位小数的尾数保留在 UMI 可用余额。"),custody_in:legacyText("从交易所资金账户的可用余额转入 UMI 或 USDT，同步记录两边的资产变动。"),custody_out:legacyText("转回交易所资金账户，可继续站内划转；链上提现以该资产已接通的网络和可用链上库存为准。"),purchase:legacyText("按认购价值确定 3 / 4 / 5 倍额度，最低 100 USDT。新单日释放 ")+this.percent(r.purchase_daily_rate)+legacyText("，从下一业务日起算。"),claim:legacyText("当前手续费 ")+this.percent(r[this.pocket+'_fee'])+legacyText("，从本次划转数量中扣除。"),treasure_deposit:legacyText("从可用 UMI 转入宝本金，下一业务日开始参与计息。"),treasure_withdraw:legacyText("当前提取手续费 ")+this.percent(r.treasure_fee)+'，'+(r.treasure_fee_source==='reserve'?legacyText("另从储备金扣除。"):legacyText("从提取数量中扣除。")),reserve_deposit:legacyText("从可用 UMI 存入储备金，用于已启用的储备扣费。"),swap:legacyText("按当前版本固定报价兑换，手续费 ")+this.percent(r.swap_fee)+legacyText("。兑换以资金池的实际可用库存为限。"),transfer:legacyText("收款人收到扣除 ")+this.percent(r.transfer_fee)+legacyText(" 手续费后的数量，请核对收款编号。"),stake:legacyText("质押后从可用余额转入 VIP 账户，可申请解押。"),unstake:legacyText("解押等待 ")+r.unstake_minutes+legacyText(" 分钟，申请时固定手续费 ")+this.percent(r.vip_fee)+'。'}[this.action];}},
  watch:{action(v){if(v==='claim'&&this.pocket==='treasure')this.pocket='referral';}},
  methods:{fmt(n){return String(n==null?'0':n).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,'');},percent(n){return (Number(n)*100).toLocaleString('zh-CN',{maximumFractionDigits:8})+'%';},statusName(s){return {active:legacyText("释放中"),paused:legacyText("已暂停"),completed:legacyText("已完成")}[s]||s;},rewardName(s){return {linear:legacyText("线性释放"),team:legacyText("团队级差"),referral:legacyText("直推奖励"),interest:legacyText("宝利息"),peer:legacyText("平级奖励")}[s]||s;},reasonName(s){return {quota_limited:legacyText("受额度限制"),excluded:legacyText("动态奖励已排除"),legacy_review:legacyText("待核对后补发")}[s]||legacyText("正常");},pocketName(s){const p=s.split(':').pop();return {main:legacyText("可用余额"),linear:legacyText("线性收益"),team:legacyText("团队收益"),referral:legacyText("直推收益"),treasure:legacyText("UMI 宝"),reserve:legacyText("储备金"),vip:legacyText("VIP 质押"),unstaking:legacyText("解押中"),points:legacyText("积分")}[p]||p;},
    operationInput(action){const v=action==='enroll'?{action,parent:this.parent||null}:{action,amount:this.amount};if(['claim','claim_to_wallet'].includes(action))v.pocket=this.pocket;if(action==='custody_in'||action==='custody_out')v.asset=this.asset;if(action==='swap'){v.asset=this.asset;v.quote_rule_id=this.state.rule_id;}if(action==='transfer')v.recipient=this.recipient;return v;},
    async submit(action){if(this.busy||this.state.read_only)return;this.busy=true;this.error='';this.message='';const v=this.operationInput(action);const draft=JSON.stringify(v);
      try{
        if(action!=='enroll'&&(!this.quote||this.quoteHash!==draft)){const {data}=await axios.post(this.route('umi.finance.preview'),v);this.quote=data;this.quoteHash=draft;return;}
        if(action!=='enroll')v.expected_rule_id=this.quote.rule_id;
        const hash=JSON.stringify(v);if(!this.pending||this.pending.hash!==hash)this.pending={hash,key:crypto.randomUUID()};v.request_key=this.pending.key;
        const {data}=await axios.post(this.route('umi.finance.submit'),v);this.message=data.message+legacyText(" · 操作编号 ")+data.operation.id;clearTimeout(this.noticeTimer);this.noticeTimer=setTimeout(()=>{this.message='';},6000);this.pending=null;this.quote=null;this.quoteHash='';this.amount='';this.$inertia.reload({preserveScroll:true});
      }catch(e){this.error=Object.values(e.response?.data?.errors||{}).flat().join('；')||legacyText("暂时无法确认结果，请保留当前输入重试，系统会校验重复操作。");if(e.response?.data?.errors?.expected_rule_id){this.quote=null;this.$inertia.reload({preserveScroll:true});}}finally{this.busy=false;}}

  }
};
</script>
