<template>
<admin-layout><Head :title="$t(&quot;UMI 本地运营 · Deepro&quot;)"/><main class="uva">
  <header class="uva-head"><div><span>UMI / OPERATIONS</span><h1>{{ $t("UMI 本地运营台") }}</h1><p>{{ $t("成员、资金、日结、提现与批次在同一套记录中核对。") }}</p></div><a href="/exchange-control-panel/umi">{{ $t("原 UMI 后台 ↗") }}</a></header>
  <div class="uva-banner"><strong>{{ $t("本地验收模式") }}</strong><span>{{ $t("测试币、模拟付款、模拟销毁和积分均不接 Deepro 真实钱包、二级市场、区块链或股票交割。") }}</span><small>{{ $t("截止（北京时间）") }}{{data.as_of}}</small></div>
  <div class="uva-metrics"><article><small>{{ $t("奖励库存 · 测试 UMI") }}</small><b>{{amount(data.reward_inventory_umi)}}</b></article><article><small>{{ $t("专户资产（含未凑齐 B）") }}</small><b>{{amount(data.dedicated_umi)}}</b></article><article><small>{{ $t("累计模拟付款") }}</small><b>{{amount(data.paid_umi)}}</b></article><article><small>{{ $t("累计模拟销毁") }}</small><b>{{amount(data.burn.simulated_confirmed_umi)}}</b></article></div>
  <p v-if="error" class="uva-error" role="alert">{{ $t(error) }}</p><p v-if="message" class="uva-ok" role="status">{{ $t(message) }}</p>
  <p :class="data.reconciliation.ok?'uva-ok':'uva-error'" role="status">{{ $t("账本对账：") }}{{data.reconciliation.ok?$t('一致'):$t('存在差异')}} · {{data.reconciliation.ledger_entries}} {{ $t("笔分录 · 未凑齐 B 已归集") }} {{amount(data.reconciliation.partial_b_umi)}} UMI <span v-for="issue in data.reconciliation.issues" :key="issue"> · {{issue}}</span></p>
  <nav class="uva-tabs" :aria-label="$t(&quot;运营模块&quot;)"><button v-for="item in tabs" :key="item.id" :class="{active:tab===item.id}" @click="tab=item.id">{{ $t(item.label) }}</button></nav>

  <div v-if="tab==='operations'" class="uva-grid"><section class="uva-card"><span class="uva-eyebrow">SANDBOX FUNDING</span><h2>{{ $t("测试资产与奖励库存") }}</h2><p>{{ $t("只能发行测试记账资产。真实钱包余额保持不变。") }}</p><label>{{ $t("向成员测试钱包入账") }}<input v-model.trim="memberId" inputmode="numeric" :placeholder="$t(&quot;成员 ID&quot;)"></label><label>{{ $t("UMI 数量") }}<input v-model.trim="fundAmount" inputmode="decimal" :placeholder="$t(&quot;例如 1000&quot;)"></label><button :disabled="busy || !memberId || !fundAmount" @click="send('fund',{member_id:memberId,amount:fundAmount})">{{ $t("发放测试 UMI") }}</button><hr><label>{{ $t("补充奖励库存 · UMI") }}<input v-model.trim="inventoryAmount" inputmode="decimal" :placeholder="$t(&quot;例如 10000&quot;)"></label><button :disabled="busy || !inventoryAmount" @click="send('inventory',{amount:inventoryAmount})">{{ $t("补充测试奖励库存") }}</button></section>
    <section class="uva-card"><span class="uva-eyebrow">{{ $t("测试入金") }}</span><h2>{{ $t("划入后自动建轮") }}</h2><p>{{ $t("模拟交易所划入或链上充值。一笔来源编号只建一轮，进入专户待销毁；不会调用真实资金或链。") }}</p><label>{{ $t("成员 ID") }}<input v-model.trim="inboundMemberId" inputmode="numeric" :placeholder="$t(&quot;成员 ID&quot;)"></label><label>{{ $t("来源") }}<select v-model="inboundSource"><option value="exchange">{{ $t("交易所测试钱包") }}</option><option value="chain">{{ $t("模拟链上充值") }}</option></select></label><label>{{ $t("数量 · UMI") }}<input v-model.trim="inboundAmount" inputmode="decimal" :placeholder="$t(&quot;例如 100&quot;)"></label><label>{{ $t("来源编号") }}<input v-model.trim="inboundRef" maxlength="80" :placeholder="$t(&quot;例如 local-transfer-001&quot;)"></label><button :disabled="busy || !inboundMemberId || !inboundAmount || !inboundRef" @click="send('inbound',{member_id:inboundMemberId,source:inboundSource,source_ref:inboundRef,amount:inboundAmount})">{{ $t("记录测试入金") }}</button></section>
    <section class="uva-card"><span class="uva-eyebrow">DAILY SETTLEMENT</span><h2>{{ $t("每日收益结算") }}</h2><p>{{ $t("静态按本金计算；V1–V9 团队级差和平级奖加速同一额度。每天只能结算一次。") }}</p><label>{{ $t("业务日期") }}<input v-model="businessDate" type="date"></label><label>{{ $t("静态日率") }}<input v-model.trim="staticRate" inputmode="decimal" placeholder="0.008–0.015"></label><button :disabled="busy || !businessDate || !staticRate" @click="send('day',{business_date:businessDate,static_rate:staticRate})">{{ $t("执行本地日结") }}</button><div class="uva-note">{{ $t("级差暂按下级当日实际静态释放计算，待业务规则最终确认。已结算日期不能修改费率重算。") }}</div></section>
    <section class="uva-card"><span class="uva-eyebrow">BURN BATCH</span><h2>{{ $t("专户模拟批次") }}</h2><p>{{ $t("把所有待批次来源统一模拟确认。入口轮次才开始释放；提现积分才进入展示。这里不会生成真实链上交易哈希。") }}</p><div class="uva-focus">{{ $t("待批次") }} {{amount(data.burn.pending_umi)}} UMI</div><button :disabled="busy || Number(data.burn.pending_umi)<=0" @click="send('batch',{})">{{ $t("模拟确认当前批次") }}</button></section>
    <section class="uva-card"><span class="uva-eyebrow">MEMBER LEVEL</span><h2>{{ $t("本地测试等级") }}</h2><p>{{ $t("正式等级按当前有效业绩升降。这里可设 V4+ 测试下限以检查平级奖；选择 V0 可恢复自动等级，不影响旧 UMI。") }}</p><label>{{ $t("成员 ID") }}<input v-model.trim="levelMemberId" inputmode="numeric" :placeholder="$t(&quot;成员 ID&quot;)"></label><label>{{ $t("V 等级") }}<select v-model.number="level"><option v-for="n in 10" :key="n" :value="n-1">V{{n-1}}</option></select></label><button :disabled="busy || !levelMemberId" @click="send('level',{member_id:levelMemberId,level})">{{ $t("设置本地测试等级") }}</button></section></div>

  <section v-if="tab==='members'" class="uva-card"><span class="uva-eyebrow">MEMBERS</span><h2>{{ $t("UMI 成员") }}</h2><p>{{ $t("业绩只统计未结束的有效轮次；余额耗尽后，当前等级会随之下降。") }}</p><div class="uva-table"><table><thead><tr><th>ID</th><th>{{ $t("Deepro 用户") }}</th><th>{{ $t("UMI 邀请码") }}</th><th>{{ $t("等级") }}</th><th>{{ $t("个人 USD") }}</th><th>{{ $t("团队 USD") }}</th><th>{{ $t("小区 USD") }}</th><th>{{ $t("测试钱包 UMI") }}</th><th>{{ $t("开通时间（北京时间）") }}</th></tr></thead><tbody><tr v-for="m in data.members" :key="m.id"><td>{{m.id}}</td><td>{{m.user_id}}</td><td>{{m.member_code}}</td><td>V{{m.level}}{{m.test_level_override?$t(' · 测试下限'):''}}</td><td>{{amount(m.performance.personal_usd)}}</td><td>{{amount(m.performance.team_usd)}}</td><td>{{amount(m.performance.small_area_usd)}}</td><td>{{amount(m.sandbox_wallet_umi)}}</td><td>{{localTime(m.joined_at)}}</td></tr></tbody></table></div><p v-if="!data.members.length">{{ $t("暂无UMI 成员。") }}</p></section>

  <section v-if="tab==='cycles'" class="uva-card"><span class="uva-eyebrow">CYCLES & DAYS</span><h2>{{ $t("轮次与日结") }}</h2><div class="uva-table"><table><thead><tr><th>{{ $t("轮次") }}</th><th>{{ $t("成员") }}</th><th>{{ $t("本金") }}</th><th>{{ $t("倍数/额度") }}</th><th>{{ $t("已释放") }}</th><th>{{ $t("状态") }}</th></tr></thead><tbody><tr v-for="c in data.cycles" :key="c.id"><td>#{{c.id}} {{ $t("/ 第") }}{{c.cycle_number}}{{ $t("轮") }}</td><td>{{c.member_id}}</td><td>{{amount(c.principal_umi)}}</td><td>{{c.multiplier}}× / {{amount(c.cap_umi)}}</td><td>{{amount(c.released_umi)}}</td><td>{{c.status}}</td></tr></tbody></table></div><h3>{{ $t("日结记录") }}</h3><div class="uva-table"><table><thead><tr><th>{{ $t("日期") }}</th><th>{{ $t("静态率") }}</th><th>{{ $t("汇总") }}</th></tr></thead><tbody><tr v-for="d in data.days" :key="d.id"><td>{{d.business_date}}</td><td>{{amount(d.static_rate)}}</td><td>{{daySummary(d.summary_json)}}</td></tr></tbody></table></div></section>

  <section v-if="tab==='withdrawals'" class="uva-card"><span class="uva-eyebrow">WITHDRAWALS</span><h2>{{ $t("提现与 B 资金来源") }}</h2><p>{{ $t("待补足的订单只能记录模拟外购转入；补足 B 后完整 W 才模拟支付。") }}</p><div class="uva-table"><table><thead><tr><th>{{ $t("单号/成员") }}</th><th>W</th><th>B</th><th>{{ $t("已有收益 / 钱包") }}</th><th>{{ $t("待外购") }}</th><th>{{ $t("模拟已付") }}</th><th>{{ $t("模拟已烧") }}</th><th>{{ $t("状态/操作") }}</th></tr></thead><tbody><tr v-for="w in data.withdrawals" :key="w.id"><td>#{{w.id}} / {{w.member_id}}</td><td>{{amount(w.requested_umi)}}</td><td>{{amount(w.required_burn_umi)}}</td><td>{{amount(w.from_income_umi)}} / {{amount(w.from_wallet_umi)}}</td><td>{{amount(w.remaining_umi)}}</td><td>{{amount(w.paid_umi)}}</td><td>{{amount(w.confirmed_burn_umi)}}</td><td>{{w.status}} <button v-if="w.status==='awaiting_topup'" :disabled="busy" @click="send('topup',{withdrawal_id:w.id})">{{ $t("模拟购入转入") }}</button></td></tr></tbody></table></div><p v-if="!data.withdrawals.length">{{ $t("暂无提现单。") }}</p></section>

  <section v-if="tab==='burn'" class="uva-card"><span class="uva-eyebrow">SOURCE LOTS & BATCHES</span><h2>{{ $t("专户来源和批次") }}</h2><p>{{ $t("真实链上已确认始终为 0；模拟批次和待处理来源分开。") }}</p><div class="uva-focus">{{ $t("累计模拟销毁") }} {{amount(data.burn.simulated_confirmed_umi)}} {{ $t("UMI · 过去 24 小时") }} {{amount(data.burn.past_24h_simulated_umi)}} {{ $t("UMI · 待销毁") }} {{amount(data.burn.pending_umi)}} UMI</div><h3>{{ $t("模拟划入与充值") }}</h3><div class="uva-table"><table><thead><tr><th>{{ $t("来源编号") }}</th><th>{{ $t("来源") }}</th><th>{{ $t("轮次") }}</th><th>UMI</th><th>{{ $t("时间") }}</th></tr></thead><tbody><tr v-for="entry in data.inbounds" :key="entry.id"><td>{{entry.request_key}}</td><td>{{entry.kind==='sandbox_inbound_chain'?$t('模拟链上充值'):$t('交易所测试钱包')}}</td><td>{{entry.source_ref}}</td><td>{{amount(entry.amount_umi)}}</td><td>{{localTime(entry.created_at)}}</td></tr></tbody></table></div><h3>{{ $t("待销毁来源") }}</h3><div class="uva-table"><table><thead><tr><th>{{ $t("来源") }}</th><th>{{ $t("类型") }}</th><th>{{ $t("成员/轮次/提现") }}</th><th>UMI</th><th>{{ $t("状态") }}</th><th>{{ $t("批次") }}</th></tr></thead><tbody><tr v-for="l in data.lots" :key="l.id"><td>{{l.source_key}}</td><td>{{l.purpose}}</td><td>{{l.member_id||'—'}} / {{l.cycle_id||'—'}} / {{l.withdrawal_id||'—'}}</td><td>{{amount(l.amount_umi)}}</td><td>{{l.status}}</td><td>{{l.batch_id||'—'}}</td></tr></tbody></table></div><h3>{{ $t("模拟批次") }}</h3><div class="uva-table"><table><thead><tr><th>{{ $t("批次") }}</th><th>UMI</th><th>{{ $t("状态") }}</th><th>{{ $t("模拟凭证") }}</th><th>{{ $t("时间（北京时间）") }}</th></tr></thead><tbody><tr v-for="b in data.batches" :key="b.id"><td>#{{b.id}}</td><td>{{amount(b.amount_umi)}}</td><td>{{b.status}}</td><td>{{b.simulation_ref}}</td><td>{{localTime(b.created_at)}}</td></tr></tbody></table></div></section>
  <div v-if="tab==='settings'" class="uva-grid"><section class="uva-card"><span class="uva-eyebrow">BSC MAINNET · CHAIN ID 56</span><h2>{{ $t("链与资金池配置") }}</h2><p>{{ $t("提现付款、奖励库存来源固定为 Deepro 内部资金池。这里只保存地址草稿；真实划转、签名与销毁始终关闭。") }}</p><label>{{ $t("UMI 合约地址") }}<input v-model.trim="tokenContract" maxlength="42" :placeholder="`已登记候选：${data.chain_settings.proposed_token_contract}`"></label><label>{{ $t("BSC 黑洞地址") }}<input v-model.trim="burnAddress" maxlength="42" placeholder="0x000000000000000000000000000000000000dEaD"></label><p class="uva-note">{{ $t("BscScan 标记的常用黑洞地址：") }}{{data.chain_settings.proposed_burn_address}}{{ $t("。提交前仍须确认 UMI 合约与此地址的代币转账规则。") }}</p><label>{{ $t("专属归集账户（可暂留空）") }}<input v-model.trim="dedicatedAddress" maxlength="42" :placeholder="$t(&quot;后续由管理员填写 0x…&quot;)"></label><button :disabled="busy" @click="send('chain_settings',{token_contract:tokenContract,burn_address:burnAddress,dedicated_address:dedicatedAddress})">{{ $t("保存地址草稿") }}</button></section><section class="uva-card"><span class="uva-eyebrow">{{ $t("接入状态") }}</span><h2>{{ $t("当前配置") }}</h2><dl><div><dt>{{ $t("网络") }}</dt><dd>BSC Mainnet · 56</dd></div><div><dt>{{ $t("提现付款") }}</dt><dd>{{ $t("Deepro 资金池") }}</dd></div><div><dt>{{ $t("奖励库存") }}</dt><dd>{{ $t("Deepro 资金池") }}</dd></div><div><dt>{{ $t("合约") }}</dt><dd>{{data.chain_settings.token_contract || $t('待确认')}}</dd></div><div><dt>{{ $t("黑洞") }}</dt><dd>{{data.chain_settings.burn_address || $t('待确认')}}</dd></div><div><dt>{{ $t("专户") }}</dt><dd>{{data.chain_settings.dedicated_address || $t('未设置')}}</dd></div><div><dt>{{ $t("真实资金操作") }}</dt><dd>{{ $t("关闭") }}</dd></div></dl><h3>{{ $t("设置记录") }}</h3><div v-if="!data.chain_settings_audit.length" class="uva-note">{{ $t("暂无地址变更") }}</div><article v-for="row in data.chain_settings_audit" :key="row.id" class="uva-audit">{{ $t("管理员") }} {{row.actor_id}} · {{localTime(row.created_at)}} {{ $t("· 请求") }} {{row.request_key}}</article></section></div>
</main></admin-layout>
</template>
<script>
import UmiLocale from '@/Functions/UmiLocale';
import AdminLayout from '@/Layouts/AdminLayout';
import axios from 'axios';
export default {mixins:[UmiLocale],components:{AdminLayout},props:{state:{type:Object,required:true}},data(){return {data:this.state,tab:'operations',busy:false,error:'',message:'',pendingKey:null,memberId:'',fundAmount:'',inventoryAmount:'',inboundMemberId:'',inboundSource:'exchange',inboundAmount:'',inboundRef:'',businessDate:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),staticRate:'0.01',levelMemberId:'',level:0,tokenContract:this.state.chain_settings?.token_contract||this.state.chain_settings?.proposed_token_contract||'',burnAddress:this.state.chain_settings?.burn_address||'',dedicatedAddress:this.state.chain_settings?.dedicated_address||'',tabs:[{id:'operations',label:this.$t("运营操作")},{id:'members',label:this.$t("成员")},{id:'cycles',label:this.$t("轮次/日结")},{id:'withdrawals',label:this.$t("提现")},{id:'burn',label:this.$t("专户/批次")},{id:'settings',label:this.$t("链与资金池")}]};},methods:{amount(v){if(v===null||v===undefined)return '0';const s=String(v);if(!/^-?\d+\.\d+$/.test(s))return s;const [whole,fraction]=s.split('.');const significant=fraction.replace(/0+$/,'');return significant?`${whole}.${significant}`:whole;},localTime(v){if(!v)return '—';const s=String(v).replace(' ','T').replace(/([+-]\d{2})$/,'$1:00');const d=new Date(s);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(d);},daySummary(v){try{const d=typeof v==='string'?JSON.parse(v):v;return `轮次 ${d.cycles} · 释放 ${this.amount(d.released_umi)} UMI · 级差 ${d.grade_rewards||0} · 平级 ${d.peer_rewards} · 烧伤 ${this.amount(d.injured_umi)} UMI`;}catch(e){return String(v||'—');}},key(){return window.crypto&&window.crypto.randomUUID?window.crypto.randomUUID():'req-'+Date.now()+'-'+Math.floor(Math.random()*1000000);},async send(action,fields){this.error='';this.message='';this.busy=true;this.pendingKey=this.pendingKey||this.key();try{const r=await axios.post('/exchange-control-panel/umi/v2',{action,request_key:this.pendingKey,...fields});this.data=r.data.state;this.pendingKey=null;this.message='操作已记录，明细已刷新。';}catch(e){this.error=(e.response&&e.response.data&&e.response.data.message)||'操作未完成；可用原请求重试';}finally{this.busy=false;}}}};
</script>
<style scoped>
.uva{--green:#1e9b52;--ink:#17261c;max-width:1450px;margin:auto;padding:30px 24px 80px;color:var(--ink)}.uva *{box-sizing:border-box}.uva-head{display:flex;justify-content:space-between;gap:18px;align-items:end}.uva-head h1{font-size:31px;font-weight:800;margin:5px 0}.uva-head p,.uva-card p{color:#617267}.uva-head>div>span,.uva-eyebrow{font-size:11px;letter-spacing:.14em;color:var(--green);font-weight:800}.uva-head a{color:var(--ink);text-decoration:underline;white-space:nowrap}.uva-banner{display:flex;gap:12px;flex-wrap:wrap;background:#eff8f1;border:1px solid #cce6d2;border-radius:14px;padding:14px 17px;margin:20px 0;color:#285338}.uva-banner small{margin-left:auto}.uva-metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.uva-metrics article,.uva-card{background:#fff;border:1px solid #dce6df;border-radius:18px;padding:19px}.uva-metrics small{display:block;color:#65746a}.uva-metrics b{display:block;font-size:26px;margin-top:6px;overflow-wrap:anywhere}.uva-tabs{display:flex;gap:8px;overflow:auto;border-bottom:1px solid #dce6df;margin:18px 0}.uva-tabs button{white-space:nowrap;padding:12px 16px;border:0;border-bottom:3px solid transparent;background:none;cursor:pointer;font-weight:700;color:#65746a}.uva-tabs button.active{border-color:var(--green);color:var(--ink)}.uva-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.uva-card h2{font-size:22px;font-weight:800;margin:8px 0 15px}.uva-card h3{font-size:18px;font-weight:700;margin:24px 0 10px}.uva-card label{display:block;font-weight:700;margin:14px 0}.uva-card input,.uva-card select{display:block;width:100%;padding:10px 12px;margin-top:6px;border:1px solid #bccfc0;border-radius:10px;background:white;color:var(--ink)}.uva-card button{background:var(--green);border:0;border-radius:10px;color:#fff;padding:10px 14px;font-weight:800;cursor:pointer}.uva-card button:disabled{opacity:.5;cursor:not-allowed}.uva-card hr{border:0;border-top:1px solid #e3eae5;margin:20px 0}.uva-note{padding:12px;border-radius:10px;background:#f5f8f6;color:#647166;margin-top:16px}.uva-focus{font-size:24px;font-weight:800;margin:20px 0}.uva-table{overflow:auto;max-width:100%}.uva table{width:100%;border-collapse:collapse;white-space:nowrap}.uva th,.uva td{text-align:left;padding:11px 12px;border-bottom:1px solid #e3eae5;font-size:13px}.uva th{color:#65746a;background:#f7faf8}.uva td button{font-size:11px;padding:6px 8px}.uva-error,.uva-ok{padding:12px 16px;border-radius:10px}.uva-error{color:#9e2424;background:#fff0ef}.uva-ok{color:#116d3c;background:#e9f8ef}@media(max-width:900px){.uva{padding:20px 14px}.uva-grid,.uva-metrics{grid-template-columns:repeat(2,1fr)}}@media(max-width:580px){.uva-grid{grid-template-columns:1fr}.uva-metrics b{font-size:20px}.uva-head{align-items:start}.uva-head h1{font-size:25px}.uva-head a{font-size:12px}.uva-banner small{margin-left:0}}
.uva-card dl>div{display:flex;justify-content:space-between;gap:16px;padding:10px 0;border-bottom:1px solid #e3eae5}.uva-card dt{color:#65746a}.uva-card dd{margin:0;text-align:right;overflow-wrap:anywhere;max-width:68%;font-weight:700}.uva-audit{border-top:1px solid #e3eae5;padding:10px 0;color:#65746a;font-size:12px;overflow-wrap:anywhere}
</style>
