@php
$t = fn($zh, $en) => str_starts_with(app()->getLocale(), 'zh') ? $zh : $en;
$reasons = [
 'DEPOSIT_ACCOUNT_UNAVAILABLE'=>$t('账户不可用，请先核实账户状态。','Account unavailable; verify the account status first.'),
 'DEPOSIT_ADDRESS_OWNERSHIP_CONFLICT'=>$t('地址归属冲突，需先核对归属证据。','Address ownership conflict; reconcile ownership evidence first.'),
 'DEPOSIT_PREDATES_ADDRESS'=>$t('交易早于地址分配，需人工核对历史。','Transaction predates address allocation; reconcile the history.'),
 'DEPOSIT_WALLET_ALLOCATION_REQUIRES_REVIEW'=>$t('钱包分配需复核。','Wallet allocation requires review.'),
 'DEPOSIT_POST_CREDIT_CHAIN_CONFLICT'=>$t('已入账交易的链上确认或区块凭证发生冲突。原入账保留，相关账户的新资金转出暂停；请核对原区块与当前区块证据后重新核验。','Chain confirmations or block evidence conflict with a credited deposit. The original credit is preserved and new outflows from the affected account are held; compare the original and current block evidence, then recheck.'),
 'DEPOSIT_RECEIPT_CONFLICT'=>$t('凭证冲突，需核对原入账记录。','Receipt conflict; reconcile the original credit.'),
 'DEPOSIT_LEGACY_RECONCILIATION_REQUIRED'=>$t('历史交易需对账，不能直接补入账。','Legacy reconciliation is required before any credit.'),
];
@endphp
<!doctype html>
<html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $t('钱包异常处理','Wallet recovery') }} · Deepro</title>
<link rel="stylesheet" href="{{ asset('css/deepro-theme.css') }}?v={{ filemtime(public_path('css/deepro-theme.css')) }}">
<style>
body{margin:0;background:var(--ui-page,#f5f6f8);color:var(--ui-text,#17202a);font:15px/1.65 system-ui}main{max-width:1300px;margin:auto;padding:28px 20px}nav{display:flex;gap:18px;flex-wrap:wrap}a{color:var(--ui-accent-text,#725100)}section{padding:22px;border:1px solid var(--ui-line,#ddd);border-radius:14px;background:var(--ui-surface,#fff);margin:22px 0}h1{font-size:28px}h2{font-size:21px;margin-top:0}p{overflow-wrap:anywhere}.table-scroll{overflow:auto}table{border-collapse:collapse;width:100%;min-width:850px;text-align:left}th,td{padding:12px;border-bottom:1px solid var(--ui-line,#ddd);vertical-align:top}th{font-size:13px}code,pre{font:12px/1.6 ui-monospace,monospace;overflow-wrap:anywhere;white-space:pre-wrap}code{display:block;max-width:260px}details pre{max-width:420px}button,select{min-height:40px;padding:8px 12px;border:1px solid var(--ui-line,#bbb);border-radius:7px;background:var(--ui-field,#fff);color:inherit}button{cursor:pointer}button:disabled{opacity:.55;cursor:not-allowed}button:focus-visible,a:focus-visible,select:focus-visible,summary:focus-visible{outline:3px solid #a98100;outline-offset:3px}.filters,.pager{display:flex;align-items:end;gap:14px;flex-wrap:wrap}.filters label{display:grid;gap:4px}.pager{margin-top:16px;justify-content:space-between}.notice{border-left:3px solid #d1a628;padding:10px 14px;background:var(--ui-field,#f8f9fa)}.error{color:var(--ui-danger,#b32e2e)}small{display:block;font-size:12px;color:var(--ui-muted,#68707c)}@media(max-width:600px){main{padding:16px 12px}section{padding:14px 12px}h1{font-size:24px}}
</style></head><body class="{{ $themeMode }}"><main>
<nav aria-label="{{ $t('钱包运营导航','Wallet operations') }}"><a href="{{ route('admin.custody') }}">{{ $t('← 托管管理','← Custody') }}</a><a href="{{ route('admin.system.monitor.wallets') }}">{{ $t('钱包运行检查','Wallet readiness') }}</a><a href="{{ route('admin.wallet.recovery') }}">{{ $t('刷新状态','Refresh status') }}</a></nav>
<h1>{{ $t('钱包异常处理','Wallet recovery') }}</h1>
<p>{{ $t('最后读取：','Last read: ') }}{{ $checkedAt }} · {{ config('app.timezone') }}</p>
<p class="notice">{{ $t('重新核验会重新检查链上凭证、地址归属与现有入账记录。只有检查通过的事件才进入正常处理；不提供直接加币、无凭证退款或清除记录。','Recheck verifies chain evidence, address ownership and existing credits. Only verified events continue through normal processing. This page does not offer direct credits, unsupported refunds or record deletion.') }}</p>
@if(!$verified)<p class="notice">{{ $t('操作前需完成托管二次验证。请进入托管管理验证后返回本页。','Complete custody verification before retrying. Verify in Custody, then return here.') }} <a href="{{route('admin.custody')}}">{{ $t('前往验证','Open verification') }}</a></p>@endif
@if(session('recovery_status'))<p role="status" class="notice">{{ session('recovery_status') }}</p>@endif
@if($errors->any())<div role="alert" class="notice error">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<section><h2>{{ $t('充值复核事件','Deposit review events') }} · {{ $events->total() }}</h2>
<form class="filters" method="get"><label>{{ $t('状态','Status') }}<select name="status">@foreach(['open'=>$t('待处理','Open'),'resolved'=>$t('已处理','Resolved'),'all'=>$t('全部','All')] as $value=>$label)<option value="{{$value}}" @selected($status===$value)>{{$label}}</option>@endforeach</select></label><label>{{ $t('网络','Network') }}<select name="chain"><option value="">{{ $t('全部','All') }}</option>@foreach($chains as $value)<option value="{{$value}}" @selected($chain===$value)>{{strtoupper($value)}}</option>@endforeach</select></label><button>{{ $t('筛选','Filter') }}</button></form>
<div class="table-scroll" tabindex="0" aria-label="{{ $t('充值复核明细，可横向滚动','Deposit review details; horizontally scrollable') }}"><table><thead><tr><th>ID / {{ $t('状态','Status') }}</th><th>{{ $t('网络与交易','Network / transaction') }}</th><th>{{ $t('原因与凭证','Reason / evidence') }}</th><th>{{ $t('处理记录','Attempts / history') }}</th><th>{{ $t('操作','Action') }}</th></tr></thead><tbody>
@forelse($events as $event)<tr><td>#{{ $event->id }}<br>{{ $event->status==='resolved'?$t('已处理','Resolved'):$t('待处理','Open') }}<small>{{ $t('充值 / 通道','Deposit / channel') }}: {{ $event->deposit_id ?? '—' }} / {{ $event->channel_id ?? '—' }}</small></td><td>{{ strtoupper($event->chain) }}<code>{{ $event->txn }}</code><small>{{ $t('事件索引','Event index') }}: {{ $event->event_index }}</small></td><td><code>{{ $event->reason }}</code><p>{{ $reasons[$event->reason] ?? $t('请核对原因码与原始业务记录；重新核验不会绕过原校验。','Reconcile this reason code with the original business records. Recheck cannot bypass validation.') }}</p><details><summary>{{ $t('查看链上凭证字段','View chain evidence fields') }}</summary><pre>{{ json_encode($event->evidence, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre></details></td><td>{{ $event->attempts }} {{ $t('次','attempts') }}<small>{{ $t('创建','Created') }}: {{ $event->created_at }}<br>{{ $t('处理','Resolved') }}: {{ $event->resolved_at ?? '—' }}</small></td><td>@if($event->status==='open')<form method="post" action="{{route('admin.wallet.recovery.retry',$event->id)}}" class="retry-form">@csrf<button type="submit" @disabled(!$verified)>{{ $t('重新核验','Recheck evidence') }}</button></form><small>{{ $t('先处理上述原因，再重试。','Resolve the cause before retrying.') }}</small>@else—@endif</td></tr>
@empty<tr><td colspan="5">{{ $t('当前筛选条件下没有复核事件。','No review events match these filters.') }}</td></tr>@endforelse
</tbody></table></div><div class="pager">@if($events->previousPageUrl())<a href="{{$events->previousPageUrl()}}">{{ $t('上一页','Previous') }}</a>@endif<span>{{ $events->currentPage() }} / {{ $events->lastPage() }}</span>@if($events->nextPageUrl())<a href="{{$events->nextPageUrl()}}">{{ $t('下一页','Next') }}</a>@endif</div>
</section>
<section><h2>{{ $t('归集失败与自动重试','Sweep failures and retries') }} · {{ $sweeps->total() }}</h2><p>{{ $t('此表展示归集异常。重试时间不代表已归集，是否完成以托管回执和链上到账为准。','A scheduled retry is not a completed sweep. Confirm completion from custody receipts and chain delivery.') }}</p><div class="table-scroll" tabindex="0"><table><thead><tr><th>{{ $t('充值 / 币种 ID','Deposit / currency ID') }}</th><th>{{ $t('状态','Status') }}</th><th>{{ $t('错误','Error') }}</th><th>{{ $t('上次尝试','Last attempt') }}</th><th>{{ $t('下次重试','Next retry') }}</th></tr></thead><tbody>@forelse($sweeps as $deposit)<tr><td>#{{$deposit->id}} / {{$deposit->currency_id}}</td><td>{{$deposit->status}} / {{$deposit->wallet_transfer_status}}</td><td><code>{{$deposit->sweep_error}}</code></td><td>{{$deposit->sweep_attempted_at ?? '—'}}</td><td>{{$deposit->sweep_retry_at ?? '—'}}</td></tr>@empty<tr><td colspan="5">{{ $t('没有已记录的归集异常。','No recorded sweep failures.') }}</td></tr>@endforelse</tbody></table></div><div class="pager">@if($sweeps->previousPageUrl())<a href="{{$sweeps->previousPageUrl()}}">{{ $t('上一页','Previous') }}</a>@endif<span>{{$sweeps->currentPage()}} / {{$sweeps->lastPage()}}</span>@if($sweeps->nextPageUrl())<a href="{{$sweeps->nextPageUrl()}}">{{ $t('下一页','Next') }}</a>@endif</div></section>
<section><h2>{{ $t('待复核或超过 30 分钟未完成的托管任务','Custody tasks under review or pending over 30 minutes') }} · {{$transfers->total()}}</h2><p>{{ $t('广播结果不明、过期或缺少终态证据的任务保留复核。请进入托管管理按原审批与回执流程处理。','Uncertain broadcasts, expiry and missing final evidence remain under review. Continue through the existing custody approval and receipt workflow.') }} <a href="{{route('admin.custody')}}">{{ $t('打开托管管理','Open Custody') }}</a></p><div class="table-scroll" tabindex="0"><table><thead><tr><th>ID / {{ $t('网络','Network') }}</th><th>{{ $t('用途 / 状态','Purpose / status') }}</th><th>{{ $t('金额与交易','Amount / transaction') }}</th><th>{{ $t('错误','Error') }}</th><th>{{ $t('创建 / 上次尝试','Created / last attempt') }}</th></tr></thead><tbody>@forelse($transfers as $transfer)<tr><td>#{{$transfer->id}} / {{strtoupper($transfer->chain)}}</td><td>{{$transfer->purpose}} / {{$transfer->status}}</td><td>{{$transfer->amount}}<code>{{$transfer->txn ?? '—'}}</code></td><td><code>{{$transfer->last_error ?? '—'}}</code></td><td>{{$transfer->created_at}}<small>{{$transfer->last_attempt_at ?? '—'}}</small></td></tr>@empty<tr><td colspan="5">{{ $t('没有符合条件的任务。','No matching custody tasks.') }}</td></tr>@endforelse</tbody></table></div><div class="pager">@if($transfers->previousPageUrl())<a href="{{$transfers->previousPageUrl()}}">{{ $t('上一页','Previous') }}</a>@endif<span>{{$transfers->currentPage()}} / {{$transfers->lastPage()}}</span>@if($transfers->nextPageUrl())<a href="{{$transfers->nextPageUrl()}}">{{ $t('下一页','Next') }}</a>@endif</div></section>
</main><script>document.querySelectorAll('.retry-form').forEach(function(form){form.addEventListener('submit',function(){form.querySelector('button').disabled=true;});});</script></body></html>
