<template><admin-layout><admin-review-panel>
<h1>{{ $t('Financial review') }}</h1>
<p class="review-notice">{{ $t('Real transfers require funded inventory and an independent reviewer. Simulation funds stay separate.') }}</p>
<dl class="review-grid"><div><dt>{{ $t('Pending transfers') }}</dt><dd>{{ checks.pending_transfers }}</dd></div><div><dt>{{ $t('Historical funding sources to review') }}</dt><dd>{{ checks.legacy_option_sources }}</dd></div><div><dt>{{ $t('Orphan role assignments') }}</dt><dd>{{ checks.orphan_roles }}</dd></div></dl>
<a class="review-link" :href="route('admin.system.monitor.wallets')">{{ $t('Wallet readiness') }}</a>
<a class="review-link" :href="route('admin.reports.wallets')">{{ $t('Wallets') }}</a>
<form @submit.prevent="filter"><label>{{ $t('Status') }} <themed-select v-model="status"><option value="">{{ $t('All') }}</option><option v-for="s in ['pending','completed','rejected']" :key="s" :value="s">{{ $t(s) }}</option></themed-select></label><button>{{ $t('Filter') }}</button></form>
<div class="review-scroll"><table><thead><tr><th>ID / {{ $t('Status') }}</th><th>{{ $t('Source wallet') }} → {{ $t('Target wallet') }}</th><th>{{ $t('Amount') }}</th><th>{{ $t('Reference') }}</th><th>{{ $t('Review') }}</th></tr></thead><tbody><tr v-for="row in transfers.data" :key="row.id"><td>{{ row.id }}<br>{{ $t(row.status) }} · {{ $t(row.funding_domain) }}</td><td>{{ row.source_wallet_id }} → {{ row.target_wallet_id }}<br>{{ row.source_field }} → {{ row.target_field }}</td><td>{{ row.amount }}<br>{{ $t('Currency') }} #{{ row.currency_id }}</td><td>{{ row.reference }}<br>{{ row.reason }}<br>{{ $t('Proposer') }} #{{ row.proposed_by }}</td><td><button v-if="row.status==='pending' && Number(row.proposed_by) !== Number($page.props.user.id)" @click="selected=row;reason=''">{{ $t('Review') }}</button><span v-else>{{ row.review_reason || '—' }}</span><details v-if="row.ledger"><summary>{{ $t('Ledger') }}</summary><pre>{{ JSON.stringify(JSON.parse(row.ledger),null,2) }}</pre></details></td></tr><tr v-if="!transfers.data.length"><td colspan="5">{{ $t('No records') }}</td></tr></tbody></table></div>
<pagination :links="transfers.links" />
<form v-if="selected" @submit.prevent="submit('approve')"><h2>{{ $t('Review') }} · {{ selected.id }}</h2><label>{{ $t('Review reason') }}<textarea v-model="reason" minlength="10" maxlength="1000" required /></label><p v-for="(message,key) in $page.props.errors" :key="key" role="alert">{{ message }}</p><button :disabled="busy">{{ $t('Approve') }}</button><button type="button" :disabled="busy || reason.trim().length<10" @click="submit('reject')">{{ $t('Reject') }}</button><button type="button" @click="selected=null">{{ $t('Cancel') }}</button></form>
</admin-review-panel></admin-layout></template>
<script>
import AdminLayout from '@/Layouts/AdminLayout';import AdminReviewPanel from '@/Components/AdminReviewPanel';import Pagination from '@/Jetstream/Pagination';
export default {components:{AdminLayout,AdminReviewPanel,Pagination},props:{transfers:Object,checks:Object,filters:Object},data(){return{status:this.filters.status||'',selected:null,reason:'',busy:false}},methods:{filter(){this.$inertia.get(this.route('admin.controls'),{status:this.status},{preserveState:true})},submit(action){if(this.busy)return;this.busy=true;this.$inertia.post(this.route('admin.controls.review',this.selected.id),{action,reason:this.reason},{onSuccess:()=>{this.selected=null},onFinish:()=>{this.busy=false}})}}};
</script>
