<template>
 <div class="dp-asset-picker">
  <button ref="trigger" type="button" class="dp-asset-picker__trigger" :id="inputId" :aria-label="$t('Select asset')" :aria-expanded="open" @click="show">
   <currency-avatar v-if="selected" :symbol="selected.symbol" :src="selected.logo || selected.full_logo_path"/>
   <span><b>{{selected ? selected.symbol : $t('Select asset')}}</b><small v-if="selected">{{selected.name}}</small></span><svg class="dp-asset-picker__chevron" viewBox="0 0 20 20" aria-hidden="true"><path d="m5 7 5 5 5-5" fill="none" stroke="currentColor" stroke-width="1.5"/></svg>
  </button>
  <section v-if="open" ref="dialog" class="dp-asset-picker__page" role="dialog" aria-modal="true" :aria-label="$t('Select asset')" @keydown="onKeydown">
   <header><button type="button" :aria-label="$t('Back')" @click="close">‹</button><h2>{{$t('Select asset')}}</h2><span/></header>
   <div class="dp-asset-picker__search"><input ref="search" v-model="search" type="search" :placeholder="$t('Search name or symbol')" :aria-label="$t('Search name or symbol')" autocomplete="off"></div>
   <nav class="dp-asset-picker__tabs" :aria-label="$t('Category')"><button type="button" :aria-pressed="category==='crypto'" @click="category='crypto'">{{$t('Crypto')}}</button><button v-if="hasStocks" type="button" :aria-pressed="category==='stocks'" @click="category='stocks'">{{$t('Stock Tokens')}}</button></nav>
   <div ref="list" class="dp-asset-picker__list">
    <section v-for="group in groups" :key="group.letter" :data-letter="group.letter"><h3>{{group.letter}}</h3><button v-for="asset in group.assets" :key="asset.symbol" type="button" @click="select(asset)" :aria-current="asset.symbol===value?'true':null"><currency-avatar :symbol="asset.symbol" :src="asset.logo || asset.full_logo_path"/><span><b>{{asset.symbol}}</b><small>{{asset.name}}</small></span><span v-if="asset.symbol===value" class="dp-asset-picker__check" aria-hidden="true">✓</span></button></section>
    <p v-if="!groups.length" role="status">{{$t('No assets found')}}</p>
   </div>
   <nav v-if="groups.length" class="dp-asset-picker__index" :aria-label="$t('Alphabet index')"><button v-for="group in groups" :key="group.letter" type="button" :aria-label="$t('Jump to')+' '+group.letter" @click="jump(group.letter)">{{group.letter}}</button></nav>
  </section>
 </div>
</template>
<script>
import CurrencyAvatar from './CurrencyAvatar.vue';
import {assetSections} from '@/Functions/AssetPicker.mjs';
export default {
 components:{CurrencyAvatar},props:{assets:{type:Array,default:()=>[]},value:String,inputId:String},
 data:()=>({open:false,category:'crypto',search:'',previousOverflow:null}),
 computed:{selected(){return this.assets.find(a=>a.symbol===this.value)},hasStocks(){return this.assets.some(a=>['stock','etf'].includes(a.asset_category))},groups(){return assetSections(this.assets,this.category,this.search)}},
 beforeDestroy(){this.restoreScroll()},
 methods:{show(){this.search='';this.category=['stock','etf'].includes(this.selected?.asset_category)?'stocks':'crypto';this.previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';this.open=true;this.$nextTick(()=>this.$refs.dialog.querySelector('button').focus())},restoreScroll(){if(this.previousOverflow!==null){document.body.style.overflow=this.previousOverflow;this.previousOverflow=null}},close(){this.open=false;this.restoreScroll();this.$nextTick(()=>this.$refs.trigger?.focus())},select(asset){this.close();if(asset.symbol!==this.value){this.$emit('input',asset.symbol);this.$emit('change',asset)}},jump(letter){const section=[...this.$refs.list.querySelectorAll('[data-letter]')].find(el=>el.dataset.letter===letter);if(section)this.$refs.list.scrollTop=section.offsetTop},onKeydown(event){if(event.key==='Escape'){event.preventDefault();this.close()}if(event.key!=='Tab')return;const items=[...this.$refs.dialog.querySelectorAll('button,input')].filter(el=>el.offsetParent!==null);const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}}
};
</script>
<style>
.dp-asset-picker__trigger>.dp-asset-picker__chevron{width:18px;height:18px;flex:0 0 18px;margin-left:auto}
.dp-asset-picker__trigger{display:flex;align-items:center;gap:10px;width:100%;min-height:52px;padding:10px 14px;border:1px solid var(--ui-line);background:var(--ui-field);border-radius:10px;color:var(--ui-text);text-align:left}.dp-asset-picker__trigger>span:nth-last-child(1){margin-left:auto}.dp-asset-picker b,.dp-asset-picker small{display:block;line-height:1.5}.dp-asset-picker b{font-size:14px}.dp-asset-picker small{font-size:12px;color:var(--ui-muted)}.dp-asset-picker__page{position:fixed;inset:0;z-index:100000;display:flex;flex-direction:column;background:var(--ui-surface);color:var(--ui-text);padding:env(safe-area-inset-top) max(16px,calc((100vw - 700px)/2)) env(safe-area-inset-bottom);overscroll-behavior:contain}.dp-asset-picker__page>header{display:flex;align-items:center;justify-content:space-between;min-height:56px;flex-shrink:0}.dp-asset-picker__page>header button,.dp-asset-picker__page>header>span{width:44px;height:44px}.dp-asset-picker__page>header button{font-size:32px;background:none;color:inherit}.dp-asset-picker__page h2{font-size:17px;font-weight:600}.dp-asset-picker__search input{width:100%;min-height:44px!important;padding:10px 14px!important;border:0!important;border-radius:9px;background:var(--ui-field)!important;color:var(--ui-text)!important;font-size:16px}.dp-asset-picker__tabs{display:flex;gap:24px;border-bottom:1px solid var(--ui-divider);flex-shrink:0}.dp-asset-picker__tabs button{background:none;color:var(--ui-muted);padding:14px 2px;min-height:48px;font-size:14px;border-bottom:2px solid transparent}.dp-asset-picker__tabs button[aria-pressed=true]{color:var(--ui-text);border-color:var(--ui-accent);font-weight:600}.dp-asset-picker__list{position:relative;flex:1;overflow:auto;overscroll-behavior:contain;padding:0 28px 24px 0;scroll-behavior:smooth}.dp-asset-picker__list h3{font-size:12px;color:var(--ui-muted);background:var(--ui-surface);padding:10px 0 6px;position:sticky;top:0;z-index:1}.dp-asset-picker__list section>button{display:flex;gap:14px;align-items:center;background:none;color:var(--ui-text);text-align:left;width:100%;min-height:64px;border-bottom:1px solid var(--ui-divider)}.dp-asset-picker__list .currency-avatar{width:34px;height:34px}.dp-asset-picker__check{margin-left:auto;color:var(--ui-accent-text)}.dp-asset-picker__index{position:absolute;right:max(4px,calc((100vw - 732px)/2));top:190px;bottom:20px;max-height:calc(100dvh - 210px);display:flex;flex-direction:column;justify-content:center;overflow:auto}.dp-asset-picker__index button{flex:0 0 auto;width:28px;min-height:20px;font-size:11px;line-height:20px;background:none;color:var(--ui-muted);padding:0}.dp-asset-picker button:focus-visible{outline:2px solid var(--ui-accent);outline-offset:-2px}
</style>
