<template><details class="mb-6 p-4 bg-white rounded shadow" @toggle="opened"><summary class="cursor-pointer font-bold">{{ $t('Market display settings') }}</summary><div v-if="form" class="mt-4">
<p class="mb-4">{{ $t('Display controls only; trading and wallet switches are unchanged.') }}</p>
<label class="block mb-4">{{ $t('Default category') }} <themed-select v-model="form.defaultCategory"><option value="crypto">{{ $t('Digital currencies') }}</option><option value="stocks">{{ $t('Stock Tokens') }}</option><option value="favorites">{{ $t('Favorites') }}</option></themed-select></label>
<label class="block mb-4"><input type="checkbox" v-model="form.firstScreen"> {{ $t('Show indicators on the first screen') }}</label><label>{{ $t('Default list') }} <themed-select v-model="form.defaultList"><option v-for="[key,label] in [['hot','Hot markets'],['gainers','Top Gainers'],['losers','Top Losers'],['new','Newly listed']]" :key="key" :value="key">{{ $t(label) }}</option></themed-select></label><div class="my-4"><span>{{ $t('Card order') }}</span><span v-for="(key,i) in form.cardOrder" :key="key" class="mx-2">{{ $t(cards.find(c=>c[0]===key)[1]) }} <button type="button" :disabled="i===0" @click="form.cardOrder.splice(i-1,0,form.cardOrder.splice(i,1)[0])">↑</button></span></div><div class="flex flex-wrap gap-4 mb-4"><label v-for="[key,label] in cards" :key="key"><input type="checkbox" v-model="form[key]"> {{ $t(label) }}</label></div>
<p>{{ $t('Sector members: use exact currency symbols separated by commas. At least two valid quotes are needed.') }}</p>
<div v-for="(sector,i) in sectors" :key="i" class="flex flex-wrap gap-2 my-3"><input v-model.trim="sector.name" :aria-label="$t('Sector name')" maxlength="24"><input v-model="sector.members" :aria-label="$t('Currency symbols')" class="flex-1"><button type="button" @click="sectors.splice(i,1)">{{ $t('Remove') }}</button></div>
<button type="button" @click="sectors.push({name:'',members:''})" :disabled="sectors.length>=12">+ {{ $t('Add sector') }}</button>
<label class="block my-4">{{ $t('Reason for change') }}<input v-model.trim="reason" maxlength="500" class="block w-full" :placeholder="$t('Reason for change')"></label><button type="button" class="px-4 py-2 bg-yellow-400 rounded" :disabled="saving || reason.length<5" @click="save">{{ $t(saving?'Saving...':'Save') }}</button><p role="status" class="my-3">{{ message }}</p>
<h3 class="font-bold mt-6">{{ $t('Data source health') }}</h3><p>CoinMarketCap · {{ $t('Source time / fetch time / failures') }}</p><div v-for="(value,key) in health" :key="key" class="my-2 text-sm"><b>{{ $t(cards.find(c=>c[0]===key)[1]) }}</b> · {{ value.value ? value.value.sourceTime+' / '+value.value.fetchedAt : $t('No data') }} · {{ value.failures }}</div>
<details class="mt-4"><summary>{{ $t('Change history') }}</summary><article v-for="event in history" :key="event.id" class="my-4 text-sm"><b>{{ event.created_at }} · #{{ event.actor_id }}</b><p>{{ event.reason }}</p><pre class="overflow-auto">{{ JSON.stringify(event.changes,null,2) }}</pre></article></details>
</div><p v-else role="status">{{ message }}</p></details></template>
<script>
import axios from 'axios';
export default {data:()=>({form:null,sectors:[],reason:'',health:{},history:[],saving:false,message:'',cards:[['global','Global crypto market cap'],['altcoin','Altcoin Season Index'],['sentiment','Fear and Greed Index'],['benchmarks','ETF Tokens'],['sparklines','Mini charts']]}),methods:{opened(e){if(e.target.open&&!this.form)this.load()},async load(){try{const {data}=await axios.get(this.route('admin.market-presentation'));this.form=data.settings;this.sectors=this.form.sectors.map(s=>({name:s.name,members:s.symbols.join(', ')}));this.health=data.health;this.history=data.history}catch(_){this.message=this.$t('Unable to load settings')}},async save(){this.saving=true;this.message='';try{await axios.put(this.route('admin.market-presentation.update'),{settings:{...this.form,sectors:this.sectors.map(s=>({name:s.name,symbols:s.members.split(/[,，\s]+/).filter(Boolean)}))},reason:this.reason});this.reason='';await this.load();this.message=this.$t('Saved')}catch(e){this.message=Object.values(e.response?.data?.errors||{}).flat().join(' ')||this.$t('Unable to save settings')}finally{this.saving=false}}}}
</script>

<style scoped>
.bg-yellow-400{background:#facc15}.my-3{margin-top:.75rem;margin-bottom:.75rem}.my-4{margin-top:1rem;margin-bottom:1rem}
</style>
