<template><section v-if="portfolio" class="umi-account"><h2>{{ $t("账户资料 ·") }} {{portfolio.nickname || portfolio.id}}</h2>
      <section class="umi-identity-strip"><div><strong>{{ portfolio.nickname || $t("UMI 用户") }}</strong><span>{{ $t("原 UID") }} {{ portfolio.id }} · {{ portfolio.uuid }}</span></div><div><span>{{ $t("原等级") }}</span><strong>{{ portfolio.level || $t("普通会员") }}</strong></div><div><span>{{ $t("直属上级") }}</span><strong>{{ portfolio.parent_id || $t("未记录") }}</strong></div><div><span>{{ $t("账户状态") }}</span><strong>{{ portfolio.activation_status === 'activated' ? $t("已关联") : $t("待激活") }}</strong></div></section>
      <div class="umi-history-note">{{ $t("账户资料与历史账务。") }}</div>
      <nav class="umi-account-tabs" :aria-label="$t(&quot;UMI 账户功能&quot;)"><a v-for="t in tabs" :key="t.id" :href="sectionUrl(t.id)" :class="{selected:section===t.id}" :aria-current="section===t.id?'page':null">{{ t.name }}</a></nav>
      <section v-if="section==='overview'" class="umi-account-content">
        <div class="umi-stat-grid"><article v-for="s in stats" :key="s.name"><span>{{ s.name }}</span><strong>{{ s.value == null ? '—' : s.value }}</strong><small>UMI</small></article></div>
        <div class="umi-two-columns"><article class="umi-panel"><h2>{{ $t("历史资产明细") }}</h2><div v-if="!portfolio.balances.length" class="umi-empty">{{ $t("原资料未记录独立余额明细") }}</div><dl v-for="b in portfolio.balances" :key="b.asset_symbol" class="umi-values"><div><dt>{{ b.asset_symbol }} {{ $t("可用") }}</dt><dd>{{ b.available_amount }}</dd></div><div><dt>{{ b.asset_symbol }} {{ $t("冻结") }}</dt><dd>{{ b.frozen_amount }}</dd></div></dl><p class="umi-muted">{{ $t("额度与累计收益分别展示，不叠加计入账户资产。") }}</p></article><article class="umi-panel"><h2>{{ $t("生态服务") }}</h2><a class="umi-service-row" :href="sectionUrl('burn')">{{ $t("燃烧与额度") }} <span>{{ $t("查看原记录 →") }}</span></a><a class="umi-service-row" :href="sectionUrl('team-income')">{{ $t("团队收益") }} <span>{{ $t("查看收益记录 →") }}</span></a><a class="umi-service-row" :href="sectionUrl('team')">{{ $t("我的团队") }} <span>{{ $t("查看直属关系 →") }}</span></a><a class="umi-service-row" :href="sectionUrl('bao')">{{ $t("UMI 宝") }} <span>{{ $t("查看账户说明 →") }}</span></a></article></div>
        <article class="umi-panel"><h2>{{ $t("累计收益") }}</h2><dl class="umi-values"><div v-for="(label,key) in earningsLabels" :key="key"><dt>{{ $t(label) }}</dt><dd>{{ portfolio.cumulative[key] == null ? '—' : portfolio.cumulative[key] }}</dd></div></dl></article>
      </section>
      <section v-else-if="section==='team'" class="umi-panel">
        <h2>{{ $t("原有团队关系") }}</h2><p class="umi-muted">{{ $t("原直属上级、层级、等级和手动等级保持不变。以下仅展示已保存范围内的成员，不重新计算返佣或晋级。") }}</p>
        <dl class="umi-values"><div><dt>{{ $t("原直属 / 原团队人数") }}</dt><dd>{{portfolio.performance.direct_invite_count == null ? $t("未记录") : portfolio.performance.direct_invite_count}} / {{portfolio.performance.total_team_count == null ? $t("未记录") : portfolio.performance.total_team_count}}</dd></div><div><dt>{{ $t("本次资料内直属 / 全部下级") }}</dt><dd>{{portfolio.team.known_direct}} / {{portfolio.team.known_descendants}}</dd></div><div><dt>{{ $t("原团队业绩") }}</dt><dd>{{portfolio.performance.team_performance == null ? $t("未记录") : portfolio.performance.team_performance}}</dd></div><div><dt>{{ $t("原小区业绩") }}</dt><dd>{{portfolio.performance.small_area_performance == null ? $t("未记录") : portfolio.performance.small_area_performance}}</dd></div><div><dt>{{ $t("原手动等级") }}</dt><dd>{{portfolio.performance.manual_level == null ? $t("未记录") : portfolio.performance.manual_level === '' ? $t("原值为空") : portfolio.performance.manual_level}}</dd></div><div><dt>{{ $t("原排除奖励标记") }}</dt><dd>{{portfolio.performance.exclude_from_rewards == null ? $t("未记录") : portfolio.performance.exclude_from_rewards ? $t("是") : $t("否")}}</dd></div></dl>
        <h3>{{ $t("原上级路径") }}</h3><p class="umi-muted">{{ $t("从本人向上追溯；范围外上级保留原编号。") }}</p><div class="umi-ancestor-path"><span>{{ $t("本人") }} {{portfolio.id}}</span><template v-for="ancestor in portfolio.team.ancestors"><b :key="'arrow-'+ancestor.id" aria-hidden="true">→</b><span :key="ancestor.id" :class="{outside:!ancestor.in_scope}">{{ancestor.id}}{{ancestor.in_scope?'':$t(" · 范围外")}}</span></template></div>
        <p v-if="portfolio.team.cycle_detected" class="umi-error">{{ $t("原关系存在循环，需要核对原始资料；当前未自动调整关系。") }}</p>
        <h3>{{ $t("已保存的多级成员") }}</h3><div class="umi-table-wrap"><table><thead><tr><th>{{ $t("原 UID") }}</th><th>{{ $t("成员") }}</th><th>{{ $t("原直属上级") }}</th><th>{{ $t("距本人层级") }}</th><th>{{ $t("原等级") }}</th></tr></thead><tbody><tr v-for="m in portfolio.team.rows" :key="m.id"><td><a v-if="adminView" :href="route('admin.umi.account',m.id)+'?section=team'">{{m.id}}</a><span v-else>{{m.id}}</span></td><td>{{m.nickname}}</td><td>{{m.parent_id}}</td><td>{{ $t("第") }} {{m.depth}} {{ $t("层") }}</td><td>{{m.level || $t("普通会员")}}</td></tr></tbody></table></div><p v-if="!portfolio.team.known_descendants" class="umi-empty">{{ $t("暂无已保存的下级成员记录") }}</p><div class="umi-pagination"><a v-if="portfolio.team.page>1" :href="sectionUrl(section,portfolio.team.page-1)">{{ $t("上一页") }}</a><span>{{ $t("共") }} {{portfolio.team.known_descendants}} {{ $t("人 ·") }} {{portfolio.team.page}} / {{portfolio.team.last_page}}</span><a v-if="portfolio.team.page<portfolio.team.last_page" :href="sectionUrl(section,portfolio.team.page+1)">{{ $t("下一页") }}</a></div>
      </section>
      <section v-else-if="section==='treasury'" class="umi-panel"><h2>{{ $t("储备金") }}</h2><dl class="umi-values"><div><dt>{{ $t("燃烧储备金 · UMI") }}</dt><dd>{{portfolio.reserve.burn_umi_balance == null ? $t("未取得") : portfolio.reserve.burn_umi_balance}}</dd></div><div><dt>{{ $t("燃烧储备金 · USDT") }}</dt><dd>{{portfolio.reserve.burn_usdt_balance == null ? $t("未取得") : portfolio.reserve.burn_usdt_balance}}</dd></div></dl><p class="umi-muted">{{ $t("储备金记录。") }}</p></section>
      <section v-else-if="section==='bao'||section==='vip'" class="umi-panel"><span class="umi-eyebrow">UMI ECOSYSTEM</span><h2>{{section==='bao'?$t("UMI 宝"):$t("VIP 质押")}}</h2><dl v-if="section==='bao'" class="umi-values"><div><dt>{{ $t("原复投宝本金 · UMI") }}</dt><dd>{{portfolio.summary['[核查]复投宝本金(UMI)'] == null ? $t("未取得") : portfolio.summary['[核查]复投宝本金(UMI)']}}</dd></div><div><dt>{{ $t("原累计 UMI 宝收益 · UMI") }}</dt><dd>{{portfolio.summary['UMI宝利润(UMI)'] == null ? $t("未取得") : portfolio.summary['UMI宝利润(UMI)']}}</dd></div><div><dt>{{ $t("原累计存入 · UMI") }}</dt><dd>{{portfolio.summary['[核查]复投宝存入总量(UMI)'] == null ? $t("未取得") : portfolio.summary['[核查]复投宝存入总量(UMI)']}}</dd></div></dl><p>{{ $t("账户权益及订单记录。") }}</p><p class="umi-muted">{{ $t("账户激活不会重新计算历史订单，也不会将登录日作为新的收益起算日。") }}</p><a :href="sectionUrl('overview')" class="umi-quiet-link">{{ $t("查看已保存的账户收益 →") }}</a></section>
      <section v-else class="umi-panel"><h2>{{currentTitle}}</h2><div class="umi-table-wrap"><table><thead><tr><th>{{ $t("原记录号") }}</th><th>{{ $t("类型") }}</th><th>{{ $t("数量") }}</th><th v-if="section==='burn'">{{ $t("原倍数 / 额度") }}</th><th v-else>{{ $t("变动后余额") }}</th><th>{{ $t("时间") }}</th></tr></thead><tbody><tr v-for="row in portfolio.history.rows" :key="row.id"><td>{{row.id}}</td><td>{{row.burn_type_name || row.type_name}}</td><td>{{row.burn_amount || row.amount}}</td><td v-if="section==='burn'">{{row.multiplier}} × / {{row.quota_granted}}</td><td v-else>{{row.balance_after}}</td><td>{{row.created_at}}</td></tr></tbody></table></div><p v-if="!portfolio.history.total" class="umi-empty">{{ $t("暂无已保存的记录") }}</p><div class="umi-pagination"><a v-if="portfolio.history.page>1" :href="sectionUrl(section,portfolio.history.page-1)">{{ $t("上一页") }}</a><span>{{ $t("共") }} {{ portfolio.history.total }} {{ $t("条") }}</span><a v-if="portfolio.history.page<portfolio.history.last_page" :href="sectionUrl(section,portfolio.history.page+1)">{{ $t("下一页") }}</a></div></section>
</section></template>
<script>
import UmiLocale from '@/Functions/UmiLocale';
import { legacyText } from '@/Functions/LegacyTranslation';


import '../Pages/Umi/umi-account.scss';
export default {mixins:[UmiLocale],
 props:{portfolio:Object,asset:Object,section:String,adminView:Boolean,availability:Object},
 data:()=>({tabs:[{id:'overview',name:legacyText("账户总览")},{id:'burn',name:legacyText("燃烧与额度")},{id:'team-income',name:legacyText("UMI 收益")},{id:'usdt',name:legacyText("USDT 流水")},{id:'team-usdt',name:legacyText("团队 USDT")},{id:'team',name:legacyText("我的团队")},{id:'treasury',name:legacyText("储备金")},{id:'bao',name:legacyText("UMI 宝")},{id:'vip',name:legacyText("VIP 质押")}],earningsLabels:{linear_release_cumulative_umi:legacyText("累计理财收益 · UMI"),team_cumulative_umi:legacyText("累计团队收益 · UMI"),referral_cumulative_umi:legacyText("累计直推收益 · UMI"),total_earnings_cumulative_umi:legacyText("累计总收益 · UMI")}}),
 computed:{stats(){const p=this.portfolio;return [{name:legacyText("历史可提资产"),value:p.dapp_balance},{name:legacyText("原总额度"),value:p.quota.total_quota},{name:legacyText("原已用额度"),value:p.quota.used_quota},{name:legacyText("原当日释放"),value:p.quota.today_released}];},currentTitle(){return (this.tabs.find(t=>t.id===this.section)||{}).name;}},
 methods:{sectionUrl(section,page=1){return '/exchange-control-panel/umi/operations?tab=archive&legacy_account='+this.portfolio.id+'&legacy_section='+section+'&legacy_page='+page;}}
};
</script>