<template><main class="umi-account"><div class="umi-account-heading"><div><span class="umi-eyebrow">UMI / ACCOUNT OPERATIONS</span><h1>{{ $t("账户管理") }}</h1><p>{{ $t("保留原有账户与关系，逐项核验身份和历史资料。") }}</p> <a :href="route('admin.umi.reconciliation')" class="umi-action">{{ $t("历史对账与规则核查 ↗") }}</a></div></div>
<div v-for="b in batches" :key="b.id" class="umi-panel"><h2>{{ $t("账户资料") }}</h2><div class="umi-admin-batches"><span>{{b.summary.users}} {{ $t("个用户") }}</span><span>{{b.summary.files}} {{ $t("份原始文件") }}</span><span>{{b.summary.external_parent_count}} {{ $t("个范围外上级") }}</span><span>{{ $t("导入时间") }} {{b.created_at}}</span></div><p class="umi-muted">{{ $t("档案与账户资金独立保存；不会因导入流水重复增加余额。邮箱归属须核定后才能开放激活。") }}</p></div>
<section class="umi-panel"><form class="umi-admin-search" @submit.prevent="searchAccounts"><input v-model="query" :aria-label="$t(&quot;原 UID 或账号标识&quot;)" :placeholder="$t(&quot;原 UID 或完整账号标识&quot;)"/><button class="umi-action">{{ $t("查找") }}</button></form><div class="umi-table-wrap"><table><thead><tr><th>{{ $t("原 UID") }}</th><th>{{ $t("用户") }}</th><th>{{ $t("上级") }}</th><th>{{ $t("原等级") }}</th><th>{{ $t("激活") }}</th><th>{{ $t("邮箱核定") }}</th><th>{{ $t("操作") }}</th></tr></thead><tbody><tr v-for="a in accounts.data" :key="a.id"><td>{{a.id}}</td><td>{{a.nickname}}<small style="display:block">{{a.uuid}}</small></td><td>{{a.parent_id||'—'}}</td><td>{{a.level||$t("普通会员")}}</td><td>{{a.activation_status==='activated'?$t("已激活"):$t("待激活")}}</td><td>{{a.contact_ready?$t("已核定"):$t("待核对")}}</td><td><a :href="route('admin.umi.account',a.id)">{{ $t("查看档案") }}</a> <button class="umi-text-button" @click="select(a)">{{ $t("核验身份") }}</button></td></tr></tbody></table></div><div class="umi-pagination"><a v-if="accounts.prev_page_url" :href="accounts.prev_page_url">{{ $t("上一页") }}</a><span>{{ $t("共") }} {{accounts.total}} {{ $t("人") }}</span><a v-if="accounts.next_page_url" :href="accounts.next_page_url">{{ $t("下一页") }}</a></div></section>
<section v-if="selected" class="umi-panel"><h2>{{ $t("核验原 UID") }} {{selected.id}}</h2><p>{{ $t("确认原账号与该邮箱的归属关系后填写依据。提交不会发送验证码；需另一位管理员复核。") }}</p><form class="umi-inline-form" @submit.prevent="propose"><label>{{ $t("核定邮箱") }}</label><input v-model="form.email" type="email" required maxlength="255"/><label>{{ $t("核验依据与工单编号") }}</label><textarea v-model="form.evidence" minlength="20" maxlength="2000" rows="4" required :placeholder="$t(&quot;记录可独立核验的依据；不要填写密码或验证码。&quot;)"/><button class="umi-action" :disabled="form.processing">{{ $t("提交复核") }}</button></form></section>
<section class="umi-panel"><h2>{{ $t("身份核验复核") }}</h2><p v-if="!reviews.length" class="umi-empty">{{ $t("暂无核验申请") }}</p><article v-for="r in reviews" :key="r.id" class="umi-values"><div><dt>{{ $t("原 UID") }} {{r.legacy_id}} · {{r.email}}</dt><dd>{{r.state==='approved'?$t("已核定"):r.state==='pending'?$t("待复核"):$t("已被后续核定替代")}}</dd></div><p>{{r.evidence}}</p><p class="umi-muted">{{ $t("提交人 #") }}{{r.proposed_by}}<span v-if="r.reviewed_by"> {{ $t("· 复核人 #") }}{{r.reviewed_by}}</span></p><button v-if="r.state==='pending'" class="umi-action" @click="approve(r.id)">{{ $t("确认归属并通过复核") }}</button></article><p v-for="(e,k) in $page.props.errors" :key="k" class="umi-error">{{e}}</p></section>
<section class="umi-panel"><h2>{{ $t("账户恢复申请") }}</h2><p v-if="!recoveryRequests.length" class="umi-empty">{{ $t("暂无恢复申请") }}</p><article v-for="r in recoveryRequests" :key="r.id" class="umi-panel"><p>{{ $t("申请编号") }} {{r.id}} · {{recoveryLabel(r.state)}}</p><p class="umi-muted">{{ $t("受理人") }} {{r.assigned_to ? "#"+r.assigned_to : $t("待受理")}} {{ $t("· 原 UID") }} {{r.legacy_id || $t("待核对")}}</p><p>{{ $t("原账号：") }}{{r.identifier}} {{ $t("· 联系邮箱：") }}{{r.reply_email}}</p><p>{{r.evidence}}</p><p class="umi-muted">{{ $t("申请人提供的联系方式仅用于沟通，不作为已验证的账户归属。完成核查后在对应用户处提交身份复核。") }}</p>
<details v-if="r.actions.length"><summary>{{ $t("查看处理记录") }}</summary><div v-for="(a,n) in r.actions" :key="n" class="umi-history-note"><strong>{{recoveryLabel(a.state)}} {{ $t("· 管理员 #") }}{{a.actor_id}}</strong><p>{{a.note}}</p><small>{{a.created_at}}</small></div></details>
<button v-if="!['resolved','rejected'].includes(r.state)" class="umi-action" @click="selectRecovery(r)">{{ $t("受理与记录") }}</button></article>
<form v-if="recoveryCase" class="umi-inline-form" @submit.prevent="saveRecovery"><h2>{{ $t("处理申请") }} {{recoveryCase.id}}</h2><label for="umi-recovery-state">{{ $t("处理状态") }}</label><themed-select id="umi-recovery-state" v-model="recoveryForm.state"><option value="in_review">{{ $t("核查中") }}</option><option value="needs_information">{{ $t("待补充资料") }}</option><option value="resolved">{{ $t("完成核定并结案") }}</option><option value="rejected">{{ $t("驳回并结案") }}</option></themed-select><label for="umi-recovery-uid">{{ $t("核对后的原 UID") }}</label><input id="umi-recovery-uid" v-model="recoveryForm.legacy_id" type="number" min="1"/><label for="umi-recovery-note">{{ $t("内部核查记录") }}</label><textarea id="umi-recovery-note" v-model="recoveryForm.note" minlength="10" maxlength="2000" rows="4" required :placeholder="$t(&quot;记录核查依据、处理结果或需要补充的资料。&quot;)"/><p class="umi-muted">{{ $t("此处保存内部记录，不向申请人发送邮件，也不会直接批准邮箱或更改原用户关系。") }}</p><button class="umi-action" :disabled="recoveryForm.processing">{{ $t("保存处理记录") }}</button><p v-for="(e,k) in recoveryForm.errors" :key="k" class="umi-error">{{e}}</p></form></section></main></template>
<script>
import UmiLocale from '@/Functions/UmiLocale';
import { legacyText } from '@/Functions/LegacyTranslation';

import '../Pages/Umi/umi-account.scss';
export default {mixins:[UmiLocale],props:{accounts:Object,reviews:Array,recoveryRequests:Array,batches:Array,search:String,asset:Object},data(){return{query:this.search,selected:null,recoveryCase:null,recoveryForm:this.$inertia.form({version:0,state:'in_review',legacy_id:null,note:''}),form:this.$inertia.form({email:'',evidence:''})}},methods:{recoveryLabel(state){return {pending:legacyText("待受理"),in_review:legacyText("核查中"),needs_information:legacyText("待补充资料"),resolved:legacyText("已核定结案"),rejected:legacyText("已驳回")}[state]||state;},selectRecovery(r){this.recoveryCase=r;this.recoveryForm.reset();this.recoveryForm.version=r.version;this.recoveryForm.legacy_id=r.legacy_id;},saveRecovery(){this.recoveryForm.post(this.route('admin.umi.recovery',this.recoveryCase.id),{onSuccess:()=>{this.recoveryCase=null;this.recoveryForm.reset();}});},searchAccounts(){this.$inertia.get(this.route('admin.umi.operations'),{tab:'archive',search:this.query});},select(a){this.selected=a;this.form.reset();},propose(){this.form.post(this.route('admin.umi.identity',this.selected.id),{onSuccess:()=>{this.selected=null;this.form.reset();}});},approve(id){this.$inertia.post(this.route('admin.umi.approve',id));}}};
</script>
