<template><admin-layout><Head :title="$t(&quot;UMI 历史权益接续 · Deepro&quot;)"/><main class="ub-page">
<div class="ub-heading"><div><span class="ub-eyebrow">UMI / CONTINUITY</span><h1>{{ $t("历史权益接续") }}</h1><p>{{ $t("以") }} {{report.cutoff}} {{ $t("的原资料登记期初，次日起继续计算；历史订单不重复执行。") }}</p></div><a :href="route('admin.umi.business')">{{ $t("收益与业务管理 →") }}</a></div>
<div class="ub-admin-summary"><article class="ub-card"><span>{{ $t("历史账户") }}</span><h2>{{report.accounts}}</h2></article><article class="ub-card"><span>{{ $t("可接续 / 待核对") }}</span><h2>{{report.ready}} / {{report.review}}</h2></article><article class="ub-card"><span>{{ $t("期初 UMI") }}</span><h2>{{summaryAmount(report.opening_umi)}}</h2></article><article class="ub-card"><span>{{ $t("原待释放日量 UMI") }}</span><h2>{{summaryAmount(report.daily_linear_umi)}}</h2></article></div>
<section class="ub-card"><h2>{{report.imported?$t("历史接续已入账"):$t("接续预览")}}</h2><p v-for="note in report.notes" :key="note">{{ $t(note) }}</p><p>{{ $t("本批登记") }} {{report.issue_limit}} {{ $t("UMI 站内发行总额；已核对的期初权益从中划入用户各分账户，剩余部分进入收益池。USDT 余额不变。") }}</p><small>{{ $t("资料指纹") }} {{report.fingerprint}}</small><p v-if="report.imported">{{ $t("批次") }} {{report.batch_id}} {{ $t("· 后续请在收益管理中预览和结算。") }}</p>
<form v-else @submit.prevent="commit"><fieldset :disabled="busy||readOnly" class="ub-fieldset"><label>{{ $t("接续依据") }}<textarea v-model.trim="reason" minlength="10" required rows="3" /></label><label><input type="checkbox" v-model="accepted" required /> {{ $t("已核对期初、范围外关系和待核对项；确认以 9 月 16 日为切换基准") }}</label><button class="ub-primary" :disabled="!accepted">{{busy?$t("正在核对并入账…"):$t("执行历史权益接续")}}</button></fieldset></form><p v-if="error" class="ub-error" role="alert">{{error}}</p></section>
<section class="ub-card"><h2>{{ $t("逐户接续清单") }}</h2><form @submit.prevent="$inertia.get(route('admin.umi.continuity'),{search:filter,result})" class="ub-filter"><label>{{ $t('Search') }}<input v-model="filter" :placeholder="$t(&quot;搜索原 UID 或待核对事项&quot;)" maxlength="100"/></label><label>{{ $t('Result') }}<themed-select v-model="result"><option value="">{{ $t('All') }}</option><option value="ready">{{ $t('可接续') }}</option><option value="review">{{ $t('待核对') }}</option></themed-select></label><button>{{ $t('Search') }}</button><Link :href="route('admin.umi.continuity')">{{ $t('Reset') }}</Link></form><div class="ub-table"><table><thead><tr><th>{{ $t("原 UID / 上级") }}</th><th>{{ $t("状态") }}</th><th>{{ $t("总额度 / 历史已用") }}</th><th>{{ $t("日释放") }}</th><th>{{ $t("期初分账户与核对事项") }}</th></tr></thead><tbody><tr v-for="a in report.rows.data" :key="a.legacy_id"><td>{{a.legacy_id}}<small>{{ $t("上级") }} {{a.parent_legacy_id||$t("无")}}</small><small v-if="a.outside_parent">{{ $t("范围外上级，原引用保留") }}</small></td><td>{{a.status==='ready'?$t("可接续"):$t("待核对")}}<small>{{a.user_id?$t("已绑定交易所账户"):$t("待用户激活或绑定")}}</small></td><td>{{fmt(a.quota_total)}}<small>{{ $t("已用") }} {{fmt(a.quota_used)}}</small></td><td>{{fmt(a.daily_release)}}</td><td><span v-for="(n,k) in a.balances" :key="k">{{names[k]}} {{fmt(n)}} · </span><p v-for="e in a.issues" :key="e" class="ub-error">{{e}}</p></td></tr></tbody></table></div><nav class="ub-pages"><Link v-if="report.rows.prev_page_url" :href="report.rows.prev_page_url" preserve-scroll>{{ $t('Previous') }}</Link><span>{{report.rows.current_page}} / {{report.rows.last_page}} · {{report.rows.total}}</span><Link v-if="report.rows.next_page_url" :href="report.rows.next_page_url" preserve-scroll>{{ $t('Next') }}</Link></nav></section>
</main></admin-layout></template>
<script>
import { legacyText } from '@/Functions/LegacyTranslation';

import AdminLayout from '@/Layouts/AdminLayout';import axios from 'axios';import '../../Umi/business.scss';
export default{components:{AdminLayout},props:{report:Object,filters:Object,readOnly:Boolean},data(){return {reason:legacyText("以 2026 年 9 月 16 日取得的原账户资料为准接续，保留原关系和历史记录。"),accepted:false,busy:false,error:'',key:null,filter:this.filters?.search||'',result:this.filters?.result||'',names:{main:legacyText("可用"),linear:legacyText("线性"),team:legacyText("团队"),referral:legacyText("直推"),treasure:legacyText("UMI 宝"),reserve:legacyText("储备")}};},methods:{summaryAmount(n){const [whole,part]=String(n??0).split('.');return whole.replace(/\B(?=(\d{3})+(?!\d))/g,',')+(part?'.'+part.slice(0,6).replace(/0+$/,''):'');},fmt(n){return String(n??'0').replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,'');},async commit(){if(!this.accepted||this.busy)return;this.busy=true;this.error='';this.key=this.key||crypto.randomUUID();try{await axios.post(this.route('admin.umi.business.submit'),{action:'continuity',fingerprint:this.report.fingerprint,reason:this.reason,request_key:this.key});this.$inertia.reload();}catch(e){this.error=Object.values(e.response?.data?.errors||{}).flat().join('；')||legacyText("接续失败，未确认入账；请刷新核对批次状态。");}finally{this.busy=false;}}}};
</script>

<style scoped>
.ub-admin-summary h2{font-size:20px;overflow-wrap:anywhere}.ub-fieldset label:has(input[type="checkbox"]){display:flex;align-items:flex-start;gap:10px;flex-direction:row}.ub-fieldset input[type="checkbox"]{width:16px;height:16px;flex:0 0 16px;margin-top:3px}.ub-card>small{overflow-wrap:anywhere}
</style>
