<template>
<admin-layout><Head :title="$t(&quot;UMI 历史对账与规则核查&quot;)"/>
 <main class="umi-account">
  <div class="umi-account-heading"><div><span class="umi-eyebrow">UMI / ACCOUNT REVIEW</span><h1>{{ $t("历史对账与规则核查") }}</h1><p>{{ $t("逐项核对原额度、资产和收益构成，保留原关系与历史差异。") }}</p></div><a :href="route('admin.umi')" class="umi-quiet-link">{{ $t("返回账户管理 ↗") }}</a></div>
  <div class="umi-history-note">{{ $t("核查不会增加余额、补发收益或更改原档案。计算一致只说明这些历史字段能对上，不代表完整结算规则或链上储备已经验证。") }}</div>
  <section class="umi-stat-grid"><article><span>{{ $t("核查账户") }}</span><strong>{{report.accounts}}</strong><small>{{report.summary_accounts}} {{ $t("人有完整 CSV 拆分") }}</small></article><article><span>{{ $t("核对一致") }}</span><strong>{{report.counts.matched}}</strong><small>{{ $t("项字段或记录检查") }}</small></article><article><span>{{ $t("待解释差异") }}</span><strong>{{report.counts.difference}}</strong><small>{{ $t("保留原值，不自动修正") }}</small></article><article><span>{{ $t("缺失或异常") }}</span><strong>{{report.counts.missing + report.counts.invalid + report.counts.ambiguous}}</strong><small>{{ $t("资料缺失、校验失败或对应不唯一") }}</small></article></section>
  <section class="umi-panel"><h2>{{ $t("核查明细") }}</h2>
   <form class="umi-review-filters" @submit.prevent="search"><div><label for="umi-audit-uid">{{ $t("原 UID") }}</label><input id="umi-audit-uid" v-model="legacyId" type="number" min="1" :placeholder="$t(&quot;全部已保存账户&quot;)"/></div><div><label for="umi-audit-state">{{ $t("核查结果") }}</label><themed-select id="umi-audit-state" v-model="state"><option value="issues">{{ $t("待核对项目") }}</option><option value="all">{{ $t("全部结果") }}</option><option value="matched">{{ $t("一致") }}</option><option value="difference">{{ $t("有差异") }}</option><option value="missing">{{ $t("缺少资料") }}</option><option value="invalid">{{ $t("校验异常") }}</option><option value="ambiguous">{{ $t("对应不唯一") }}</option><option value="notice">{{ $t("保留说明") }}</option></themed-select></div><button class="umi-action">{{ $t("查询") }}</button><a class="umi-quiet-link" :href="downloadUrl">{{ $t("下载完整核查结果 ↓") }}</a></form>
   <p v-for="(error,key) in $page.props.errors" :key="key" class="umi-error">{{error}}</p>
   <div class="umi-table-wrap"><table><thead><tr><th>{{ $t("原 UID") }}</th><th>{{ $t("核查项目与来源") }}</th><th>{{ $t("结果") }}</th><th>{{ $t("原值 / 对照值 / 差额") }}</th></tr></thead><tbody><tr v-for="(c,i) in checks.rows" :key="i"><td><a :href="route('admin.umi.account',c.legacy_id)">{{c.legacy_id}}</a></td><td class="umi-review-detail"><strong>{{ $t(c.label) }}</strong><small>{{ $t(c.source) }}</small><p v-if="c.note">{{ $t(c.note) }}</p></td><td><span class="umi-result" :class="'umi-result-'+c.state">{{stateName(c.state)}}</span></td><td class="umi-review-amount"><div>{{ $t("原值：") }}{{c.actual == null ? '—' : c.actual}}</div><div>{{ $t("对照：") }}{{c.expected == null ? '—' : c.expected}}</div><div v-if="c.delta!=null">{{ $t("差额：") }}{{c.delta}} {{c.unit}}</div></td></tr></tbody></table></div>
   <p v-if="!checks.total" class="umi-empty">{{ $t("当前筛选条件下没有记录") }}</p><div class="umi-pagination"><a v-if="checks.page>1" :href="pageUrl(checks.page-1)">{{ $t("上一页") }}</a><span>{{checks.page}} / {{checks.last_page}} {{ $t("· 共") }} {{checks.total}} {{ $t("项") }}</span><a v-if="checks.page<checks.last_page" :href="pageUrl(checks.page+1)">{{ $t("下一页") }}</a></div>
  </section>
  <section class="umi-panel"><h2>{{ $t("接续功能与当前状态") }}</h2><p>{{ $t("日结、收益领取、交易所资金账户划转及补发管理已实现。历史规则的证据完整度与当前接续状态分别列示。") }}</p><p v-if="runtime.imported">{{ $t("已登记") }} {{runtime.openings}} {{ $t("个历史账户期初 · 截止") }} {{runtime.cutoff}} {{ $t("· 已绑定交易所账户") }} {{runtime.linked_accounts}} {{ $t("个。") }}</p><p v-else>{{ $t("历史期初尚未登记，原用户尚未开始接续计息。请在历史权益接续页面核对登记情况。") }}</p><p>{{runtime.writable?$t("业务操作已开放；实际领取仍需完成历史接续、身份绑定并满足余额及额度条件。"):$t("当前环境只允许查看业务。")}}</p><a :href="route('admin.umi.business')">{{ $t("进入业务管理 →") }}</a> · <a :href="route('admin.umi.continuity')">{{ $t("历史权益接续 →") }}</a></section>
  <section class="umi-panel"><h2>{{ $t("原机制核查进度") }}</h2><p>{{ $t("依据日期") }} {{evidence.observed_on}} {{ $t("· 复核") }} {{evidence.reviewed_on}}{{ $t("。已复算结论、新系统实现和无法唯一恢复的原历史参数分别说明。") }}</p><div class="umi-rule-grid"><article v-for="rule in evidence.rules" :key="rule.id" class="umi-rule-card"><span class="umi-status-pill">{{ruleName(rule.status)}}</span><h3>{{rule.name}}</h3><p>{{rule.known}}</p><strong>{{ $t("接续实现") }}</strong><p>{{rule.implementation}}</p><strong>{{ $t("尚不能唯一确认") }}</strong><p>{{rule.missing}}</p><small>{{ $t("来源：") }}{{rule.sources.map(sourceName).join('、')}}</small></article></div></section>
  <section class="umi-panel"><h2>{{ $t("本次核查范围") }}</h2><p>{{ $t(report.scope) }}</p><p>{{ $t("已删除燃烧记录") }} {{report.deleted_burn_records}} {{ $t("条，保留档案，不恢复权益。") }}</p><p class="umi-muted">{{ $t("生成时间") }} {{report.generated_at}} {{ $t("· 资料指纹") }} {{report.snapshot_fingerprint}}</p><p class="umi-muted">{{ $t("本页校验结构化档案和流水；全部附件内容的完整性仍由独立归档校验检查。") }}</p></section>
 </main>
</admin-layout>
</template>
<script>
import { legacyText } from '@/Functions/LegacyTranslation';

import AdminLayout from '@/Layouts/AdminLayout';import '../../Umi/umi-account.scss';
export default {components:{AdminLayout},props:{runtime:Object,report:Object,evidence:Object,checks:Object,filters:Object},data(){return {legacyId:this.filters.legacy_id||'',state:this.filters.state};},computed:{downloadUrl(){return this.route('admin.umi.reconciliation')+'?'+new URLSearchParams({...(this.filters.legacy_id?{legacy_id:this.filters.legacy_id}:{}),format:'json'});}},methods:{search(){this.$inertia.get(this.route('admin.umi.reconciliation'),{...(this.legacyId?{legacy_id:this.legacyId}:{}),state:this.state});},pageUrl(page){return this.route('admin.umi.reconciliation')+'?'+new URLSearchParams({...this.filters,legacy_id:this.filters.legacy_id||'',page});},stateName(v){return {matched:legacyText("一致"),difference:legacyText("有差异"),missing:legacyText("缺少资料"),invalid:legacyText("校验异常"),ambiguous:legacyText("对应不唯一"),notice:legacyText("保留说明")}[v]||v;},ruleName(v){return {preserved:legacyText("原样保留"),historical_verified:legacyText("历史字段可复算"),incomplete:legacyText("规则待补齐"),conflicting:legacyText("历史费率存在差异"),sample_reconstructed:legacyText("样本已复算"),client_verified:legacyText("客户端规则可确认"),unidentifiable:legacyText("现有证据无法唯一恢复")}[v]||v;},sourceName(id){return (this.evidence.sources.find(s=>s.id===id)||{}).label||id;}}};
</script>
