<template><ops-shell title="Asset workbench" description="Inspect asset, network and user-facing rules together. Configuration checks do not prove a completed transfer." :tabs="tabs">
<form class="ops-form ops-card" @submit.prevent="search"><label>{{ $t('Asset') }}<themed-select v-model="asset"><option value="">{{ $t('All') }}</option><option v-for="a in options" :key="a.id" :value="a.id">{{ a.symbol }}</option></themed-select></label><div class="ops-actions"><button type="submit" class="ops-primary">{{ $t('Inspect configuration') }}</button></div></form>
<p class="ops-muted">{{ $t('Changes use the existing editors and approvals. Return here after saving to verify the effective configuration.') }}</p>
<section class="ops-card" v-for="a in assets.data" :key="a.id"><h2>{{ a.symbol }} · {{ a.name }}</h2><span class="ops-status" :class="a.enabled?'ok':'bad'">{{ $t(a.enabled?'Enabled':'Disabled') }}</span><span v-if="a.bsc_only" class="ops-status">BSC / BEP20</span><div class="ops-links"><Link v-for="l in a.links" :key="l.url" :href="l.url">{{ $t(l.label) }} ↗</Link></div><p v-if="!a.networks.length">{{ $t('No network is linked to this asset') }}</p>
<article class="ops-card" v-for="n in a.networks" :key="n.id"><h3>{{ n.name }} · {{ n.chain || '—' }}</h3><ops-fields :record="{kind:n.kind,contract:n.contract,decimals:n.decimals,channel_id:n.channel_id,channel_state:n.channel_state,updated_at:n.updated_at}"/><details><summary>{{ $t('Configuration version') }}</summary><p>{{ n.config_digest || '—' }}</p></details>
<div class="ops-grid"><section><h3>{{ $t('User deposit preview') }}</h3><p class="ops-status" :class="n.public_deposit.available?'ok':'bad'">{{ $t(n.public_deposit.message || 'Available') }}</p><ops-fields :record="n.deposit_rules"/><p v-if="n.deposit_issue">{{ $t('Operational reason') }}: {{ $t(n.deposit_issue) }}</p></section><section><h3>{{ $t('User withdrawal preview') }}</h3><p class="ops-status" :class="n.public_withdrawal.available?'ok':'bad'">{{ $t(n.public_withdrawal.message || 'Available') }}</p><ops-fields :record="n.withdrawal_rules"/><p v-if="n.withdrawal_issue">{{ $t('Operational reason') }}: {{ $t(n.withdrawal_issue) }}</p></section><section><h3>{{ $t('Scanner evidence') }}</h3><ops-fields :record="n.scanner"/></section><section><h3>{{ $t('Automatic collection') }}</h3><ops-fields :record="{auto_sweep:n.auto_sweep,fee_funding_enabled:n.fee_funding_enabled}"/><p v-for="issue in n.collection_issues" :key="issue">{{ $t(issue) }}</p><p v-if="!n.collection_issues.length">{{ $t('Network automation configured; execution requires fees and verified receipts') }}</p><p>{{ $t('Cold storage rules') }}: {{ n.cold_rules.length }}</p><ops-fields v-for="rule in n.cold_rules" :key="rule.id" :record="rule"/></section></div><div class="ops-links"><Link v-for="l in n.links" :key="l.url" :href="l.url">{{ $t(l.label) }} ↗</Link></div></article></section>
<p v-if="!assets.data.length">{{ $t('No records') }}</p><pagination :links="assets.links"/>
</ops-shell></template>
<script>
import OpsShell from './Shell';import OpsFields from './Fields';import Pagination from '@/Jetstream/Pagination';
export default {components:{OpsShell,OpsFields,Pagination},props:{tabs:Array,assets:Object,options:Array,filters:Object,checked_at:String},data(){return {asset:this.filters.asset||''}},methods:{search(){this.$inertia.get(this.route('admin.operations.assets'),this.asset?{asset:this.asset}:{})}}};
</script>
