<template><ops-shell title="User service overview" description="Review authorized user records and assign service responsibility without changing financial records or referral relationships." :tabs="tabs"><form class="ops-form ops-card" @submit.prevent="find"><label>{{ $t('User ID') }}<input v-model="userId" type="number" min="1" required></label><div class="ops-actions"><button type="submit" class="ops-primary">{{ $t('Open user overview') }}</button><Link v-if="userListUrl" :href="userListUrl">{{ $t('Users') }} ↗</Link></div></form>
<section v-if="!subject && queue" class="ops-card"><h2>{{ $t('Active service cases') }}</h2><p class="ops-muted">{{ $t('Up to 100 active cases in your existing user scope, ordered by due date.') }}</p><p v-if="!queue.length">{{ $t('No records') }}</p><article class="ops-record" v-for="c in queue" :key="c.id"><Link :href="route('admin.operations.user',{user:c.user_id})">{{ $t('User ID') }} #{{ c.user_id }}</Link><ops-fields :record="c"/></article></section>
<teams v-if="teamDirectory" :teams="teamDirectory"/><template v-if="subject"><section class="ops-card"><h2>#{{ subject.id }} · {{ subject.name }}</h2><ops-fields :record="subject"/><div class="ops-links"><Link :href="profile_url">{{ $t('User profile') }} ↗</Link><Link v-if="referral_url" :href="referral_url">{{ $t('Referral center') }} ↗</Link></div></section>
<div class="ops-grid"><section class="ops-card" v-for="m in modules" :key="m.type"><h2>{{ $t(m.label) }}</h2><p v-if="!m.allowed">{{ $t('Not available within your permissions') }}</p><template v-else><p v-for="s in m.counts" :key="s.status">{{ $t(s.status) }}: {{ s.count }}</p><p v-if="!m.rows.length">{{ $t('No records') }}</p><article v-for="row in m.rows" :key="row.id" class="ops-record"><Link :href="row.url">{{ row.reference || '#'+row.id }}</Link><p>{{ $t(row.status) }} <span v-if="row.amount">· {{ row.amount }} {{ row.symbol }}</span></p><p v-if="row.title">{{ row.title }}</p></article><p class="ops-muted">{{ $t('Latest 10 records') }}</p><Link :href="m.url">{{ $t('Open module') }} ↗</Link></template></section></div>
<section class="ops-card"><h2>{{ $t('Service responsibility') }}</h2><p class="ops-muted">{{ $t('The operator must already have access to this user. Assignment does not grant permissions.') }}</p><p v-if="assignee">{{ $t('Responsible operator ID') }}: #{{ assignee.id }} · {{ assignee.name }}</p><case-form :record="serviceCase" :teams="teams" :url="route('admin.operations.user.update',{user:subject.id})"/></section>
<section class="ops-card"><h2>{{ $t('Orders') }}</h2><p v-if="orders===null">{{ $t('Not available within your permissions') }}</p><p v-else-if="!orders.length">{{ $t('No records') }}</p><article v-for="o in orders || []" :key="o.id"><Link :href="route('admin.operations.trace',{type:'order',reference:o.id})">{{ o.id }}</Link><ops-fields :record="o"/></article><p class="ops-muted">{{ $t('Latest 10 records') }}</p></section>
<section class="ops-card"><h2>{{ $t('Independent referral relationships') }}</h2><div class="ops-grid"><section><h3>{{ $t('Exchange referral') }}</h3><ops-fields :record="exchange_referral"/></section><section><h3>{{ $t('UMI referral') }}</h3><p v-if="umi_referral===null">{{ $t('Not available within your permissions') }}</p><p v-else-if="!umi_referral.length">{{ $t('No records') }}</p><ops-fields v-for="u in umi_referral || []" :key="u.id" :record="u"/></section></div></section><section class="ops-card"><timeline :events="history"/></section></template>
</ops-shell></template>
<script>
import OpsShell from './Shell';import OpsFields from './Fields';import Timeline from './Timeline';import CaseForm from './CaseForm';import Teams from './Teams';
export default {components:{OpsShell,OpsFields,Timeline,CaseForm,Teams},props:{tabs:Array,subject:Object,case:Object,assignee:Object,history:Array,modules:Array,orders:Array,exchange_referral:Object,umi_referral:Array,profile_url:String,referral_url:String,userListUrl:String,queue:Array,teams:Array,teamDirectory:Array},data(){return {userId:this.subject?this.subject.id:''}},computed:{serviceCase(){return this.$props.case}},methods:{find(){this.$inertia.get(this.route('admin.operations.users'),{user_id:this.userId})}}};
</script>
