<template><admin-layout><main class="execution-settings"><h1>{{ $t('Spot execution') }}</h1>
<p>{{ $t('External prices only. No external orders. Credit is a platform obligation, not deposited reserves.') }}</p>
<article class="pool"><h2>{{ $t('Platform credit pool') }}</h2>
<div class="pool-metrics"><div><span>{{ $t('Shared credit limit') }}</span><strong>{{ amount(pool.credit_limit) }} USDT</strong></div><div><span>{{ $t('Used credit') }}</span><strong>{{ amount(pool.used) }} USDT</strong></div><div><span>{{ $t('Available credit') }}</span><strong>{{ amount(pool.available) }} USDT</strong></div><div><span>{{ $t('Book USDT position') }}</span><strong>{{ amount(pool.quote_position) }} USDT</strong></div><div><span>{{ $t('Realized trading PnL') }}</span><strong>{{ amount(pool.realized_pnl) }} USDT</strong></div></div>
<p>{{ $t('Pool credit cannot be withdrawn or transferred. Customer trade proceeds follow normal withdrawal rules.') }}</p>
<p v-if="!pool.marks_fresh" role="alert">{{ $t('Missing fresh quotes. Only exposure-reducing fills are available.') }}</p>
<form @submit.prevent="savePool"><label>{{ $t('Shared credit limit') }} (USDT)<input v-model="poolForm.credit_limit" inputmode="decimal" /></label><label>{{ $t('Status') }}<themed-select v-model="poolForm.enabled"><option :value="false">{{ $t('Disabled') }}</option><option :value="true">{{ $t('Enabled') }}</option></themed-select></label><label>{{ $t('Default pool for USDT markets') }}<themed-select v-model="poolForm.default_for_usdt"><option :value="false">{{ $t('Disabled') }}</option><option :value="true">{{ $t('Enabled') }}</option></themed-select></label><label>{{ $t('Reason') }}<input v-model="poolForm.reason" maxlength="500" required /></label><button :disabled="busy!==null">{{ $t('Save') }}</button></form><p role="status">{{ messages.pool }}</p>
<p>{{ $t('Explicit market settings override the default. New eligible USDT markets share this pool.') }}</p>
<div class="execution-audits"><table><thead><tr><th>{{ $t('Market') }}</th><th>{{ $t('Platform inventory or liability') }}</th><th>{{ $t('Average entry price') }}</th><th>{{ $t('Short risk price') }}</th></tr></thead><tbody><tr v-for="p in pool.positions" :key="p.currency_id"><td>{{ name(p.market_id) }}</td><td>{{ amount(p.quantity) }}</td><td>{{ amount(p.average_price) }}</td><td>{{ amount(p.risk_price) }}</td></tr></tbody></table></div>
<p>{{ $t('Negative inventory is owed by the platform. Positive book balances do not prove on-chain reserves.') }}</p>
<h2>{{ $t('Credit fills') }}</h2><div class="execution-audits"><table><thead><tr><th>ID</th><th>{{ $t('Market') }}</th><th>{{ $t('Side') }}</th><th>{{ $t('Quantity') }}</th><th>{{ $t('Price') }}</th><th>{{ $t('Status') }}</th><th>{{ $t('Used credit') }}</th></tr></thead><tbody><tr v-for="f in pool.fills" :key="f.id"><td>{{ f.id }}</td><td>{{ name(f.market_id) }}</td><td>{{ $t(f.maker_side==='buy'?'Buy':'Sell') }}</td><td>{{ amount(f.quantity) }}</td><td>{{ amount(f.price) }}</td><td>{{ $t(f.status==='settled'?'Completed':'Pending') }}</td><td>{{ amount(f.credit_after) }}</td></tr></tbody></table></div>
<h2>{{ $t('Audit log') }}</h2><div class="execution-audits"><table><thead><tr><th>{{ $t('Date') }}</th><th>{{ $t('User ID') }}</th><th>{{ $t('Reason') }}</th><th>{{ $t('Shared credit limit') }}</th><th>{{ $t('Status') }}</th></tr></thead><tbody><tr v-for="a in pool.audits" :key="a.id"><td>{{ a.created_at }}</td><td>{{ a.actor_id }}</td><td>{{ a.reason }}</td><td>{{ amount(parsed(a.after).credit_limit) }}</td><td>{{ $t(parsed(a.after).enabled?'Enabled':'Disabled') }}</td></tr></tbody></table></div>
</article>
<article v-for="m in markets" :key="m.id"><h2>{{ m.name }}</h2><p v-if="m.mode==='platform_maker'">{{ $t('Available') }}: {{ m.base_available }} {{ m.base }} · {{ m.quote_available }} {{ m.quote }}</p>
<p>{{ $t('Executable depth') }}: {{ $t('Buy') }} {{ m.bids }} / {{ $t('Sell') }} {{ m.asks }}</p>
<form @submit.prevent="save(m)"><label>{{ $t('Execution mode') }}<themed-select v-model="forms[m.id].mode"><option value="default">{{ $t('Use global settings') }}</option><option value="internal">{{ $t('Internal order matching') }}</option><option value="platform_maker">{{ $t('Funded platform maker') }}</option><option v-if="m.quote==='USDT'" value="platform_credit">{{ $t('Platform credit pool') }}</option></themed-select></label>
<label v-if="forms[m.id].mode==='platform_maker'">{{ $t('Maker user ID') }}<input v-model="forms[m.id].maker_user_id" type="number" min="1" /></label>
<label>{{ $t('Maximum quote per fill') }} ({{ m.quote }})<input v-model="forms[m.id].max_quote_per_fill" inputmode="decimal" /></label><button :disabled="busy!==null">{{ $t('Save') }}</button></form><p role="status">{{ messages[m.id] }}</p></article>
<h2>{{ $t('Audit log') }}</h2><div class="execution-audits"><table><thead><tr><th>{{ $t('Date') }}</th><th>{{ $t('Market') }}</th><th>{{ $t('User ID') }}</th><th>{{ $t('Execution mode') }}</th></tr></thead><tbody><tr v-for="a in audits" :key="a.id"><td>{{ a.created_at }}</td><td>{{ name(a.market_id) }}</td><td>{{ a.actor_id }}</td><td>{{ auditMode(a) }}</td></tr></tbody></table></div>
</main></admin-layout></template>
<script>
import AdminLayout from '@/Layouts/AdminLayout';
export default {components:{AdminLayout},props:{markets:Array,audits:Array,pool:Object},watch:{markets(value){this.forms=Object.fromEntries(value.map(m=>[m.id,{mode:m.configured_mode,maker_user_id:m.maker_user_id,max_quote_per_fill:String(Number(m.max_quote_per_fill))}]))}},data(){return{busy:null,messages:{},poolForm:{enabled:this.pool.enabled,default_for_usdt:this.pool.default_for_usdt,credit_limit:String(Number(this.pool.credit_limit)),reason:''},forms:Object.fromEntries(this.markets.map(m=>[m.id,{mode:m.configured_mode,maker_user_id:m.maker_user_id,max_quote_per_fill:String(Number(m.max_quote_per_fill))}]))}},methods:{parsed(v){return typeof v==='string'?JSON.parse(v):v},amount(v){return Number(v||0).toLocaleString(undefined,{maximumFractionDigits:8})},name(id){return this.markets.find(m=>m.id===id)?.name||id},auditMode(a){const d=this.parsed(a.after);return this.$t(d.mode==='platform_credit'?'Platform credit pool':d.mode==='platform_maker'?'Funded platform maker':'Internal order matching')},savePool(){this.busy='pool';this.$inertia.put(this.route('admin.spot-credit-pool'),this.poolForm,this.options('pool'))},options(id){return{preserveScroll:true,onSuccess:()=>this.$set(this.messages,id,this.$t('Settings saved')),onError:e=>this.$set(this.messages,id,Object.values(e).join(' ')),onFinish:()=>{this.busy=null}}},save(m){this.busy=m.id;this.$inertia.put(this.route('admin.spot-execution.update',m.id),this.forms[m.id],this.options(m.id))}}};
</script>
<style scoped>
.execution-settings{max-width:1440px;margin:auto;padding:clamp(16px,3vw,36px);color:var(--ui-text)}h1{font-size:26px;font-weight:700;margin-bottom:16px}h2{font-size:18px;font-weight:600}p{margin:10px 0;line-height:1.6}article{border:1px solid var(--ui-line);background:var(--ui-surface);border-radius:12px;padding:20px;margin:20px 0}form{display:flex;gap:16px;align-items:end;flex-wrap:wrap}label{display:grid;gap:8px;flex:1 1 200px}input,select{width:100%;padding:10px;background:var(--ui-field);color:var(--ui-text);border:1px solid var(--ui-line);border-radius:8px}button{padding:12px 24px;border-radius:8px;background:#f0c932;color:#161a22;font-weight:600}button:disabled{opacity:.5}.execution-audits{overflow:auto}table{width:100%;text-align:start}td,th{padding:12px;border-bottom:1px solid var(--ui-line)}
</style>
<style scoped>.pool-metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:18px;margin:20px 0}.pool-metrics span{display:block;font-size:13px;color:var(--ui-text-muted)}.pool-metrics strong{display:block;font-size:20px;margin-top:6px}.pool form{margin-top:20px}.pool h2{margin-top:20px}.pool td{white-space:nowrap}</style>
