<template><admin-layout><Head :title="$t('理财负债与兑付')"/><main class="term-ops">
  <h1>{{ $t('理财负债与兑付') }}</h1><p>{{ $t('按币种核对本金、应付收益和到期兑付；本表为站内账面负债，不代表链上资产证明。') }}</p>
  <p>{{ $t('结算时区') }}: {{report.timezone}} · {{report.queried_at}}</p>
  <form method="get"><label>{{ $t('用户 ID') }}<input name="user_id" :value="report.filters.user_id" inputmode="numeric"></label><label>{{ $t('币种 ID') }}<input name="currency_id" :value="report.filters.currency_id" inputmode="numeric"></label><label>{{ $t('状态') }}<select name="status" :value="report.filters.status || ''"><option value="">{{ $t('全部') }}</option><option value="active">{{ $t('进行中') }}</option><option value="completed">{{ $t('已完成') }}</option><option value="redeemed">{{ $t('提前赎回') }}</option></select></label><label>{{ $t('到期自') }}<input name="due_from" type="date" :value="report.filters.due_from"></label><label>{{ $t('到期至') }}<input name="due_to" type="date" :value="report.filters.due_to"></label><label><input type="checkbox" name="failed" value="1" :checked="report.filters.failed">{{ $t('仅失败待处理') }}</label><button>{{ $t('筛选') }}</button><a :href="exportUrl">{{ $t('导出当前筛选') }}</a></form>
  <div class="table-scroll"><table><thead><tr><th>{{ $t('币种') }}</th><th>{{ $t('在持本金') }}</th><th>{{ $t('已计提收益') }}</th><th>{{ $t('平台应付收益') }}</th><th>{{ $t('历史预留收益') }}</th><th>{{ $t('已到期应付本息') }}</th><th>{{ $t('7 天内含逾期') }}</th><th>{{ $t('30 天内含逾期') }}</th><th>{{ $t('累计实付收益') }}</th></tr></thead><tbody><tr v-for="r in report.totals" :key="r.currency_id"><td>{{symbol(r.currency_id)}}</td><td>{{r.active_principal}}</td><td>{{r.accrued_reward}}</td><td>{{r.platform_reward_due}}</td><td>{{r.reserved_reward}}</td><td>{{r.matured_payable}}</td><td>{{r.due_7d_payable}}</td><td>{{r.due_30d_payable}}</td><td>{{r.paid_reward}}</td></tr></tbody></table></div>
  <p>{{ $t('平台到期支付产品不以预存收益作为申购条件。计提收益包含在约定总收益中，不重复相加；逾期金额已包含在未来 7 天及 30 天内。') }}</p>
  <p v-if="message" role="status">{{message}}</p><p v-if="error" role="alert">{{error}}</p>
  <div class="table-scroll"><table><thead><tr><th>ID / {{ $t('用户') }}</th><th>{{ $t('币种') }}</th><th>{{ $t('本金') }}</th><th>{{ $t('约定收益') }}</th><th>{{ $t('周期收益率 / 单利年化') }}</th><th>{{ $t('起息 / 到期') }}</th><th>{{ $t('状态') }}</th><th>{{ $t('兑付处理') }}</th></tr></thead><tbody><tr v-for="r in report.positions.data" :key="r.id"><td>#{{r.id}} / {{r.user_id}}</td><td>{{symbol(r.currency_id)}}</td><td>{{r.principal}}</td><td>{{r.term_reward}}</td><td>{{r.period_return_pct}}% / {{r.annualized_simple_pct}}%</td><td>{{r.value_date}}<br>{{r.redemption_date}}</td><td>{{r.status}}</td><td><template v-if="r.settlement_task">{{r.settlement_task.error_code || r.settlement_task.status}} · {{r.settlement_task.attempts}}</template><template v-if="r.status==='active' && new Date(r.redemption_date)<=new Date(report.queried_at)"><input v-model.trim="reasons[r.id]" :placeholder="$t('填写核对依据（至少 10 字）')"><button :disabled="busy || (reasons[r.id]||'').length<10" @click="retry(r.id)">{{ $t('重试到期兑付') }}</button></template></td></tr><tr v-if="!report.positions.data.length"><td colspan="8">{{ $t('暂无记录') }}</td></tr></tbody></table></div>
  <pagination :links="report.positions.links"/><h2>{{ $t('近期导出与重试审计') }}</h2><div class="table-scroll"><table><tr><th>ID</th><th>{{ $t('操作人') }}</th><th>{{ $t('操作') }}</th><th>{{ $t('依据') }}</th><th>{{ $t('时间') }}</th></tr><tr v-for="e in report.history" :key="e.id"><td>{{e.id}}</td><td>{{e.actor_id}}</td><td>{{e.object_type}} / {{e.object_id}} / {{e.action}}</td><td>{{e.reason}}</td><td>{{e.created_at}}</td></tr></table></div>
</main></admin-layout></template>
<script>
import UmiLocale from '@/Functions/UmiLocale';
import AdminLayout from '@/Layouts/AdminLayout';
import Pagination from '@/Jetstream/Pagination';
import axios from 'axios';
export default {mixins:[UmiLocale],components:{AdminLayout,Pagination},props:{report:Object},data(){return {busy:false,reasons:{},message:'',error:''};},computed:{exportUrl(){const p=new URLSearchParams(this.report.filters);p.delete('page');return '/exchange-control-panel/staking/operations/export?'+p.toString();}},methods:{symbol(id){return this.report.currencies.find(c=>c.id===id)?.symbol || id;},async retry(id){this.busy=true;this.error='';try{await axios.post('/exchange-control-panel/staking/operations/retry',{stake_id:id,reason:this.reasons[id]});this.$inertia.reload({only:['report'],preserveScroll:true});this.message=this.$t('已完成核对，请以更新后的订单和流水为准。');}catch(e){this.error=e.response?.data?.message||this.$t('处理失败，请查看错误记录。');}finally{this.busy=false;}}}};
</script>
<style scoped>.term-ops{max-width:100%;padding:20px}.term-ops h1{font-size:25px;font-weight:700}.term-ops h2{margin:24px 0 12px;font-size:19px}.term-ops p{margin:12px 0}.term-ops form{display:flex;flex-wrap:wrap;gap:12px;margin:20px 0;align-items:end}.term-ops label{display:flex;flex-direction:column;gap:5px}.term-ops input,.term-ops select{border:1px solid #94a3b8;border-radius:5px;padding:8px;max-width:220px}.term-ops button,.term-ops a{padding:8px 12px;background:#243653;color:#fff;border-radius:5px}.term-ops button:disabled{opacity:.5}.table-scroll{max-width:100%;overflow:auto}table{min-width:100%;border-collapse:collapse}th,td{text-align:left;border-bottom:1px solid #cbd5e1;padding:12px;white-space:nowrap}body.dark input,body.dark select{background:#182334;color:#e2e8f0}</style>
