<template>
 <app-layout><div class="btc-admin">
  <header><div><h1>{{ $t('BTC wallet management') }}</h1><p>{{ $t('Core holds signing keys. Old deposit addresses remain monitored after a switch.') }}</p></div><Link :href="route('admin.custody')">{{ $t('Wallet custody') }} ↗</Link></header>
  <section><div v-if="!twoFactorConfigured"><Link href="/user/profile/2fa?lite=1">{{ $t('Set up authenticator') }} ↗</Link></div>
   <form v-else-if="!verified" @submit.prevent="verify"><label>{{ $t('Authenticator code') }}<input v-model="code" maxlength="6" inputmode="numeric" autocomplete="one-time-code"></label><button :disabled="busy">{{ $t('Verify') }}</button></form><p v-else>{{ $t('Verified for five minutes') }}</p>
   <p>{{ $t('Wallet switching requires another administrator to review. Saving a proposal does not move funds.') }}</p>
  </section>
  <p v-if="error" class="error" role="alert">{{ error }}</p>
  <section><h2>{{ $t('Node status') }}</h2><p v-if="nodeError" class="error">{{ $t(nodeError) }}</p><div v-else class="grid"><div>{{ $t('Network') }}: {{node.chain}}</div><div>{{ $t('Block height') }}: {{node.blocks}} / {{node.headers}}</div><div>{{ $t('Sync progress') }}: {{((node.verificationprogress||0)*100).toFixed(4)}}%</div></div><p v-if="currentWallet">{{ $t('Current wallet') }}: {{currentWallet.name}} · {{ $t('Available balance') }}: {{currentWallet.balances.trusted}} BTC</p><p>{{ $t('Pending transfer tasks') }}: {{pendingTransfers}}</p></section>
  <section v-if="canConfigure"><h2>{{ $t('Connect a Core wallet') }}</h2><form @submit.prevent="submit('connect',connect)"><label>{{ $t('Wallet name') }}<input v-model="connect.name" required pattern="[A-Za-z0-9][A-Za-z0-9_-]{0,63}" list="core-wallets"><datalist id="core-wallets"><option v-for="name in available" :key="name" :value="name"/></datalist></label><label class="check"><input type="checkbox" v-model="connect.create">{{ $t('Create a descriptor wallet if it does not exist') }}</label><button :disabled="busy||!verified">{{ $t('Connect wallet') }}</button></form><p>{{ $t('Register the original Core wallet first. No private keys are entered or displayed here.') }}</p></section>
  <section><h2>{{ $t('Core wallets') }}</h2><div class="wallet-grid"><article v-for="w in wallets" :key="w.id"><h3>{{w.name}} · {{ $t(w.status) }}</h3><code>{{w.address}}</code><p>{{ $t('Available balance') }}: {{w.balances ? w.balances.trusted : '—'}} BTC</p><p>{{ $t('Pending balance') }}: {{w.balances ? w.balances.untrusted_pending : '—'}} BTC</p><p>{{ $t('Signing status') }}: {{ $t(w.can_sign?'Ready':'Not ready') }}</p><p v-if="w.scanning">{{ $t('Wallet scan progress') }}: {{((w.scanning.progress||0)*100).toFixed(2)}}%</p><p>{{ $t('Last scan') }}: {{w.scan.checked_at||'—'}}</p><p>{{ $t('Last backup') }}: {{w.backup_at||'—'}}</p><p v-if="w.scan.error" class="error">{{$t(w.scan.error)}}</p><p v-if="w.error" class="error">{{$t(w.error)}}</p><div v-if="canConfigure" class="actions"><button :disabled="busy||!verified" @click="submit('backup',{wallet_id:w.id})">{{ $t('Create server backup') }}</button><button :disabled="busy||!verified||!w.backup_at||w.id===control.active_wallet_id" @click="submit('propose',{wallet_id:w.id})">{{ $t('Propose wallet switch') }}</button></div>
   <form v-if="canConfigure && control.active_wallet_id && w.id!==control.active_wallet_id" @submit.prevent="submit('migrate',{wallet_id:w.id,amount:migration[w.id]})"><label>{{ $t('Migration amount') }} (BTC)<input v-model="migration[w.id]" inputmode="decimal" required></label><button :disabled="busy||!verified">{{ $t('Create migration for review') }}</button></form>
  </article></div><p>{{ $t('Backups remain on the private Core server. A backup timestamp does not prove a recovery drill passed.') }}</p></section>
  <section v-if="control.proposed_wallet_id"><h2>{{ $t('Wallet switch review') }}</h2><p>{{ $t('Current wallet') }}: {{walletName(control.active_wallet_id)}} → {{walletName(control.proposed_wallet_id)}}</p><p>{{ $t('Requested by') }}: {{control.proposed_by}} · {{ $t('Revision') }}: {{control.revision}}</p><button :disabled="busy||!verified||control.proposed_by===actorId||pendingTransfers>0" @click="submit('approve',{revision:control.revision})">{{ $t('Approve wallet switch') }}</button></section>
  <section v-if="canConfigure"><h2>{{ $t('BTC transfer settings') }}</h2><form @submit.prevent="submit('configure',settings)"><div class="grid"><label>{{ $t('Native transfer fee cap') }} (BTC)<input v-model="settings.max_fee" inputmode="decimal" required></label><label>{{ $t('Maximum fee rate') }} (sat/vB)<input v-model="settings.max_fee_rate" type="number" min="1" max="10000" step="0.0001" required></label><label>{{ $t('Confirmations') }}<input v-model="settings.confirmations" type="number" min="6" max="1000" required></label></div><label class="check"><input v-model="settings.enabled" type="checkbox">{{ $t('Enable BTC managed transfers') }}</label><label class="check"><input v-model="settings.auto_cold" type="checkbox">{{ $t('Automatically execute approved cold rules') }}</label><p>{{ $t('Automatic cold transfers require an approved destination rule and preserve pending withdrawals and the hot reserve.') }}</p><button :disabled="busy||!verified">{{ $t('Save') }}</button></form></section>
  <section><h2>{{ $t('Cold storage and transfer history') }}</h2><Link :href="route('admin.cold_storage.create')">{{ $t('Create Cold Storage') }} ↗</Link><p><Link :href="route('admin.custody')">{{ $t('View rules, approvals and transaction receipts') }} ↗</Link></p></section>
 </div></app-layout>
</template>
<script>
import AppLayout from '@/Layouts/AdminLayout.vue';
import {Link} from '@inertiajs/vue2';
export default {components:{AppLayout,Link},props:['currentWallet','wallets','available','node','nodeError','control','network','verified','twoFactorConfigured','canConfigure','actorId','pendingTransfers'],
 data(){return{code:'',error:'',busy:false,connect:{name:'',create:false},migration:{},settings:{enabled:this.network.enabled,auto_cold:this.control.auto_cold,max_fee:String(this.network.native_max_fee).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,''),max_fee_rate:this.control.max_fee_rate,confirmations:this.network.confirmations}}},
 methods:{walletName(id){return (this.wallets.find(w=>w.id===id)||{}).name||this.$t('Original default wallet')},submit(action,data){this.error='';this.busy=true;this.$inertia.post(route('admin.bitcoin.action',action),data,{preserveScroll:true,onError:errors=>{this.error=Object.values(errors).flat().map(e=>this.$t(e)).join(' ')},onFinish:()=>{this.busy=false}})},async verify(){this.busy=true;this.error='';try{await axios.post(route('admin.cold_storage.google.verify'),{code:this.code});this.code='';this.$inertia.reload({only:['verified']})}catch(e){this.error=this.$t('CUSTODY_2FA_INVALID')}finally{this.busy=false}}}}
</script>
<style scoped>
.btc-admin{max-width:1280px;margin:0 auto;padding:24px;color:var(--ui-text,#222)}header,.actions{display:flex;justify-content:space-between;gap:12px;flex-wrap:wrap}h1{font-size:24px}h2{font-size:19px;margin-bottom:14px}h3{font-size:16px}section,article{padding:20px;border:1px solid #c8ad68;border-radius:10px;margin:18px 0;background:var(--ui-surface,#fff)}p{margin:10px 0;line-height:1.7}code{display:block;overflow-wrap:anywhere;font-size:12px}.grid,.wallet-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:16px}label{display:flex;flex-direction:column;gap:8px;margin:12px 0}input{color:inherit;background:transparent;border:1px solid #b2b6c0;border-radius:6px;padding:9px;max-width:100%}.check{flex-direction:row;align-items:center}button{background:#f3cc39;color:#1c2230;border-radius:6px;padding:10px 15px;margin:5px 0}button:disabled{opacity:.45;cursor:not-allowed}.error{color:#d5344b}a{text-decoration:underline}@media(max-width:600px){.btc-admin{padding:12px}section,article{padding:14px}.grid,.wallet-grid{grid-template-columns:1fr}}
</style>
