<template>
 <app-layout>
  <div class="custody-page">
   <div class="custody-heading"><div><h1>{{ $t('Wallet custody') }}</h1><p>{{ $t('Deposits, sweeps, hot wallets and cold storage') }}</p></div><Link :href="route('admin.cold_storage.create')" class="custody-button">{{ $t('Create Cold Storage') }}</Link></div>
   <section class="custody-panel custody-security">
    <template v-if="!twoFactorConfigured"><b>{{ $t('Two-factor authentication required') }}</b><Link href="/user/profile/2fa?lite=1">{{ $t('Set up authenticator') }} ↗</Link></template>
    <template v-else-if="!verified"><label for="custody-otp">{{ $t('Authenticator code') }}</label><input id="custody-otp" v-model="code" inputmode="numeric" autocomplete="one-time-code" maxlength="6"><button class="custody-button" @click="verify" :disabled="busy">{{ $t('Verify') }}</button></template>
    <span v-else>{{ $t('Verified for five minutes') }}</span>
    <p>{{ $t('Blank cold addresses stay disabled. Configuration changes require independent approval.') }}</p>
   </section>
   <div v-if="error" role="alert" class="custody-error">{{ error }}</div>
   <section class="custody-panel"><h2>{{ $t('Networks') }}</h2><p><Link :href="route('admin.bitcoin')">{{ $t('BTC wallet management') }} ↗</Link></p><Link href="/exchange-control-panel/deposit-channels">{{ $t('Asset automation checklist') }} ↗</Link><p>{{ $t('Fee caps are limits, not charges. Native and token transfers use separate limits.') }}</p><p>{{ $t('Choose the automatic sweep scope once. Eligible deposits are collected without individual approval.') }}</p><div class="custody-networks">
    <form v-for="n in localNetworks" :key="n.chain" :id="'network-'+n.chain" class="custody-network" @submit.prevent="saveNetwork(n)">
     <h3>{{ chainName(n.chain) }}</h3><code>{{ n.hot_address || $t('Not configured') }}</code>
     <p>{{ $t(n.key_configured ? 'Signing key configured' : 'Signing key missing') }}</p>
     <label>{{ $t('Native transfer fee cap') }} ({{ nativeSymbol(n.chain) }})<input v-model="n.native_max_fee" inputmode="decimal" required></label>
     <label>{{ $t('Token transfer fee cap') }} ({{ nativeSymbol(n.chain) }})<input v-model="n.max_fee" inputmode="decimal" required></label>
     <label>{{ $t('Daily gas funding limit') }} ({{ nativeSymbol(n.chain) }})<input v-model="n.daily_gas_limit" inputmode="decimal" required></label>
     <p v-if="Number(n.daily_gas_limit)===0">{{ $t('Automatic fee funding is disabled; deposit addresses need native fees or delegated resources') }}</p>
     <p v-if="n.chain==='tron'">{{ $t('TRX transfers use bandwidth. TRC20 transfers also use Energy. Delegated Energy is detected on-chain; no rental provider is connected.') }}</p>
     <label>{{ $t('Confirmations') }}<input v-model="n.confirmations" type="number" min="1" required></label>
     <label class="custody-check"><input v-model="n.enabled" type="checkbox">{{ $t('Enable custody') }}</label>
     <label class="custody-check"><input v-model="n.auto_sweep" type="checkbox">{{ $t('Automatically approve verified sweeps') }}</label>
     <label>{{ $t('Automatic sweep scope') }}<themed-select v-model="n.auto_sweep_scope"><option value="new_live">{{ $t('New production deposits only') }}</option><option value="all_verified">{{ $t('All verified deposits, including pilot and pending sweeps') }}</option></themed-select></label>
     <p v-if="n.auto_sweep && n.auto_sweep_scope==='all_verified'">{{ $t('Saving authorizes automatic on-chain collection of eligible pending and future deposits to the configured hot wallet.') }}</p>
     <button class="custody-button" :disabled="busy || !verified">{{ $t('Save') }}</button>
    </form>
   </div></section>
   <section class="custody-panel"><h2>{{ $t('Cold storage rules') }}</h2><p v-if="!rules.length">{{ $t('No cold address configured. Create a disabled draft and fill the address later.') }}</p>
    <div class="custody-table"><table v-if="rules.length"><thead><tr><th>{{ $t('Asset') }}</th><th>{{ $t('Address') }}</th><th>{{ $t('Threshold / transfer') }}</th><th>{{ $t('Hot reserve / daily limit') }}</th><th>{{ $t('Status') }}</th><th>{{ $t('Actions') }}</th></tr></thead>
     <tbody><tr v-for="r in rules" :key="r.id"><td>{{r.symbol}}<small>{{r.network_name}}</small></td><td class="custody-address">{{r.address || $t('Not configured')}}</td><td>{{short(r.cold_min_balance_amount)}} / {{short(r.cold_transfer_amount)}}</td><td>{{short(r.hot_reserve)}} / {{short(r.daily_limit)}}</td><td>{{ $t(r.status ? 'Active' : r.address ? 'Awaiting approval' : 'Draft') }}</td><td><Link :href="route('admin.cold_storage.edit',r.id)">{{ $t('Edit') }}</Link><button v-if="!r.status && r.address" :disabled="busy || !verified" @click="action('rule',r.id,'approve')">{{ $t('Approve and enable') }}</button><button v-if="r.status" :disabled="busy || !verified" @click="action('rule',r.id,'pause')">{{ $t('Pause') }}</button></td></tr></tbody></table></div>
   </section>
   <section class="custody-panel"><h2>{{ $t('Transfer tasks') }}</h2><p>{{ $t('Transfers between platform wallets do not credit users again.') }}</p>
    <div class="custody-table"><table><thead><tr><th>ID</th><th>{{ $t('Type') }}</th><th>{{ $t('Network') }}</th><th>{{ $t('Amount') }}</th><th>{{ $t('Status') }}</th><th>{{ $t('Transaction') }}</th><th>{{ $t('Actions') }}</th></tr></thead>
     <tbody><tr v-for="t in transfers.data" :key="t.id"><td>{{t.id}}</td><td>{{ $t(t.purpose) }}</td><td>{{chainName(t.chain)}}</td><td>{{short(t.sent_amount || t.amount)}} {{t.symbol}}</td><td>{{ $t(t.status) }}<small v-if="t.automation_reason">{{ $t(t.automation_reason) }}</small><small v-else-if="t.last_error" class="custody-error">{{ $t(t.last_error) }}</small></td><td class="custody-address"><a v-if="explorer(t)" :href="explorer(t)" target="_blank" rel="noopener noreferrer">{{t.txn}}</a><span v-else>{{t.txn || '—'}}</span></td><td><button v-if="['tron','ethereum','bnb','polygon','xlayer'].includes(t.chain) && ['approved','awaiting_approval'].includes(t.status)" @click="estimate(t)" :disabled="busy">{{ $t('Check resources and fee') }}</button><button v-if="t.status==='awaiting_approval'" @click="action('transfer',t.id,'approve')" :disabled="busy || !verified">{{ $t('Approve') }}</button><button v-if="['approved','awaiting_approval'].includes(t.status) && t.purpose!=='withdrawal'" @click="action('transfer',t.id,'cancel')" :disabled="busy || !verified">{{ $t('Cancel') }}</button><button v-if="['cancelled','failed'].includes(t.status) && t.purpose!=='withdrawal'" @click="action('transfer',t.id,'resume')" :disabled="busy || !verified">{{ $t('Resume') }}</button><button v-if="['confirming','review'].includes(t.status)" @click="action('transfer',t.id,'recheck')" :disabled="busy || !verified">{{ $t('Check receipt') }}</button></td></tr>
     <tr v-if="!transfers.data.length"><td colspan="7">{{ $t('No transfer tasks yet') }}</td></tr></tbody></table></div>
    <div v-if="quote" role="status" class="custody-panel"><b>#{{quote.id}} · {{ $t('Resource quote') }}</b><p>{{ $t('Estimated native fee') }}: {{quote.fee}} {{nativeSymbol(quote.chain)}} · {{ $t('Native balance') }}: {{quote.native_balance}} · {{ $t('Native fee shortfall') }}: {{quote.native_shortfall}}</p><p v-if="quote.energy_required">Energy: {{quote.energy_available}} / {{quote.energy_required}} · {{ $t('Energy shortfall') }}: {{quote.energy_shortfall}}</p><p>{{ $t('Read-only estimate. No rental, signing or transfer is performed.') }}</p></div>
    <div class="custody-pages"><Link v-if="transfers.prev_page_url" :href="transfers.prev_page_url">← {{ $t('Previous') }}</Link><span>{{transfers.current_page}} / {{transfers.last_page}}</span><Link v-if="transfers.next_page_url" :href="transfers.next_page_url">{{ $t('Next') }} →</Link></div>
   </section>
   <section class="custody-panel"><h2>{{ $t('Wallet access') }}</h2><form @submit.prevent="grant" class="custody-security"><label>{{ $t('User ID') }}<input v-model="userId" type="number" min="1" required></label><label class="custody-check"><input type="checkbox" v-model="grantEnabled">{{ $t('Enable custody access') }}</label><button class="custody-button" :disabled="busy || !verified">{{ $t('Save') }}</button><small>{{ $t('Only super administrators can change wallet access.') }}</small></form></section>
   <section class="custody-panel"><h2>{{ $t('入金银行卡') }}</h2><form @submit.prevent="saveBank"><label>{{ $t('入金银行卡') }}<textarea v-model="bankForm.address" rows="3" maxlength="2000"></textarea></label><label class="custody-check"><input type="checkbox" v-model="bankForm.status">{{ $t('Active') }}</label><button class="custody-button" :disabled="busy || !verified">{{ $t('Save') }}</button></form></section>
   <section class="custody-panel"><h2>{{ $t('Audit log') }}</h2><form @submit.prevent="$inertia.get(route('admin.custody'),{...auditForm,audit_page:1},{preserveScroll:true})" class="custody-security"><label>{{ $t('Network') }}<themed-select v-model="auditForm.audit_chain"><option value="">{{ $t('All') }}</option><option v-for="chain in ['bitcoin','ethereum','bnb','polygon','xlayer','tron','solana','ton']" :key="chain" :value="chain">{{chainName(chain)}}</option></themed-select></label><label>{{ $t('Asset') }}<themed-select v-model="auditForm.audit_currency"><option value="">{{ $t('All') }}</option><option v-for="c in auditAssets" :key="c.id" :value="c.id">{{c.symbol}}</option></themed-select></label><label>{{ $t('User ID') }}<input type="number" min="1" v-model="auditForm.audit_actor"></label><label>{{ $t('Transfer') }}<input type="number" min="1" v-model="auditForm.audit_transfer"></label><label>{{ $t('Action') }}<input v-model="auditForm.audit_action" maxlength="100"></label><label>{{ $t('Start time') }}<input type="date" v-model="auditForm.audit_start"></label><label>{{ $t('End time') }}<input type="date" v-model="auditForm.audit_end"></label><button class="custody-button">{{ $t('Search') }}</button><Link :href="route('admin.custody')" preserve-scroll>{{ $t('Reset') }}</Link><a :href="auditExportUrl" class="custody-button">{{ $t('Export applied audit filters') }}</a></form><p>{{ $t('Audit dates use UTC. Legacy rule events may use the current rule association; deleted rules without snapshots remain unclassified.') }}</p><div class="custody-table"><table><thead><tr><th>{{ $t('Date') }}</th><th>{{ $t('User ID') }}</th><th>{{ $t('Action') }}</th><th>{{ $t('Network') }} / {{ $t('Asset') }}</th><th>{{ $t('Transfer') }}</th></tr></thead><tbody><tr v-for="a in audits.data" :key="a.id"><td>{{a.created_at}}</td><td>{{a.actor_id || '—'}}</td><td>{{a.action}}<details><summary>{{ $t('Details') }}</summary><pre style="white-space:pre-wrap;max-width:480px;overflow-wrap:anywhere">{{JSON.stringify(a.detail,null,2)}}</pre></details></td><td>{{a.chain ? chainName(a.chain) : '—'}} / {{a.symbol || '—'}}</td><td>{{a.transfer_id || '—'}}</td></tr></tbody></table></div><nav class="custody-pages"><Link v-if="audits.prev_page_url" :href="audits.prev_page_url" preserve-scroll>{{ $t('Previous') }}</Link><span>{{audits.current_page}} / {{audits.last_page}} · {{audits.total}}</span><Link v-if="audits.next_page_url" :href="audits.next_page_url" preserve-scroll>{{ $t('Next') }}</Link></nav></section>
  </div>
 </app-layout>
</template>
<script>
import AppLayout from '@/Layouts/AdminLayout';
export default {components:{AppLayout},props:{networks:Array,bank:Object,rules:Array,transfers:Object,audits:Object,auditFilters:Object,auditAssets:Array,auditExportUrl:String,twoFactorConfigured:Boolean,verified:Boolean},
 data(){return {auditForm:{audit_chain:'',audit_currency:'',...this.auditFilters},bankForm:{address:this.bank?.address||'',status:!!this.bank?.status},localNetworks:this.networks.map(x=>({...x,auto_sweep_scope:x.auto_sweep_scope || 'new_live',native_max_fee:String(x.native_max_fee ?? x.max_fee),max_fee:String(x.max_fee).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,''),daily_gas_limit:String(x.daily_gas_limit).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,'')})),quote:null,code:'',error:'',busy:false,userId:'',grantEnabled:true}},
 methods:{
  async estimate(t){this.busy=true;this.error='';this.quote=null;try{const r=await axios.get('/exchange-control-panel/custody/transfers/'+t.id+'/estimate');this.quote={...r.data,id:t.id,chain:t.chain}}catch(e){this.error=e.response?.data?.message||this.$t('CUSTODY_RESOURCE_ESTIMATE_UNAVAILABLE')}finally{this.busy=false}},
  short(v){return String(v).replace(/(\.\d*?)0+$/,'$1').replace(/\.$/,'')},
  nativeSymbol(v){return {ethereum:'ETH',bnb:'BNB',polygon:'POL',xlayer:'OKB',tron:'TRX',solana:'SOL',ton:'TON'}[v]},
  chainName(v){return {bitcoin:'Bitcoin',ethereum:'Ethereum',bnb:'BNB Smart Chain',polygon:'Polygon',xlayer:'X Layer',tron:'TRON',solana:'Solana',ton:'TON'}[v] || v},
  explorer(t){const root={bitcoin:'https://mempool.space/tx/',ethereum:'https://etherscan.io/tx/',bnb:'https://bscscan.com/tx/',polygon:'https://polygonscan.com/tx/',xlayer:'https://www.okx.com/web3/explorer/xlayer/tx/',tron:'https://tronscan.org/#/transaction/',solana:'https://solscan.io/tx/'}[t.chain];return t.txn && root ? root+encodeURIComponent(t.txn) : null},
  options(){return {preserveScroll:true,onStart:()=>{this.busy=true;this.error=''},onFinish:()=>this.busy=false,onError:e=>{this.error=Object.values(e).flat().map(v=>this.$t(v)).join(' ')}}},
  async verify(){this.busy=true;this.error='';try{await axios.post('/exchange-control-panel/cold-storage/google-verify',{code:this.code});this.code='';this.$inertia.reload({only:['verified']})}catch(e){this.error=Object.values(e.response?.data?.errors||{}).flat().map(v=>this.$t(v)).join(' ')||this.$t('Verification failed')}finally{this.busy=false}},
  async saveBank(){this.busy=true;this.error='';try{await axios.put('/exchange-control-panel/cold-storage/1/deposit-bank-card',this.bankForm)}catch(e){this.error=Object.values(e.response?.data?.errors||{}).flat().map(v=>this.$t(v)).join(' ')||this.$t('Verification failed')}finally{this.busy=false}},
  saveNetwork(n){this.$inertia.put(this.route('admin.custody.network',n.chain),{enabled:n.enabled,auto_sweep:n.auto_sweep,auto_sweep_scope:n.auto_sweep_scope,max_fee:n.max_fee,native_max_fee:n.native_max_fee,daily_gas_limit:n.daily_gas_limit,confirmations:n.confirmations},this.options())},
  action(kind,id,action){this.$inertia.post(this.route('admin.custody.action',{kind,id,action}),{},this.options())},
  grant(){this.$inertia.post(this.route('admin.custody.grant'),{user_id:this.userId,enabled:this.grantEnabled},this.options())}
 }}
</script>
<style scoped>
.custody-page{max-width:1600px;margin:auto;color:var(--ui-text,#222)}h1{font-size:28px;font-weight:700}h2{font-size:20px;font-weight:650;margin-bottom:14px}h3{font-weight:650;margin-bottom:8px}p,small{color:var(--ui-muted,#667085);line-height:1.6}p{margin:8px 0 16px}small{display:block}.custody-heading,.custody-security,.custody-pages{display:flex;align-items:center;gap:16px;flex-wrap:wrap}.custody-heading{justify-content:space-between;margin-bottom:24px}.custody-panel{padding:24px;border:1px solid var(--ui-line,#d8c7a5);border-radius:16px;background:var(--ui-surface,#fff);margin-bottom:20px}.custody-networks{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:20px}.custody-network{padding:20px;border:1px solid var(--ui-line,#d8c7a5);border-radius:12px;min-width:0}.custody-network code{display:block;font-size:12px;overflow-wrap:anywhere}.custody-page label{display:block;font-size:13px;margin:12px 0}.custody-page select,.custody-page textarea,.custody-page input:not([type=checkbox]){display:block;background:var(--ui-page,#f9fafb);border:1px solid var(--ui-line,#d8c7a5);color:inherit;border-radius:8px;padding:10px;width:100%;min-width:0;font-size:16px}.custody-page input:focus-visible,.custody-page button:focus-visible,.custody-page a:focus-visible{outline:2px solid #be922b;outline-offset:3px}.custody-page .custody-check{display:flex;gap:10px;align-items:center}.custody-button{display:inline-block;background:linear-gradient(110deg,#ffecad,#ddb45d);color:#272113;padding:10px 18px;border-radius:9px;font-weight:600}.custody-page button:disabled{opacity:.5;cursor:not-allowed}.custody-table{overflow-x:auto}.custody-table table{min-width:760px}.custody-page table{width:100%;border-collapse:collapse;text-align:left;font-size:13px}.custody-page th,.custody-page td{padding:14px 12px;border-bottom:1px solid var(--ui-line,#d8c7a5);vertical-align:top}.custody-page th{color:var(--ui-muted,#667085);font-weight:500}.custody-address{max-width:260px;overflow-wrap:anywhere}.custody-page td button,.custody-page td a{display:inline-block;color:var(--ui-accent-text,#987019);margin:0 10px 8px 0}.custody-error{color:var(--ui-danger,#b42318);overflow-wrap:anywhere}.custody-pages{justify-content:flex-end;padding-top:16px}@media(max-width:1100px){.custody-networks{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:640px){.custody-networks{grid-template-columns:1fr}.custody-panel{padding:16px}.custody-network{padding:16px}.custody-page h1{font-size:24px}}
</style>
