<template><ticket-layout><Head><title>{{ticket.title}}</title></Head><h1>{{ticket.title}}</h1><p class="ticket-meta">#{{ticket.ticket_id}} · {{ $t(statuses[ticket.status]) }}</p>
<p v-if="success" role="status" class="ticket-notice">{{success}}</p><article class="ticket-card"><h2>{{ $t('Your request') }}</h2><p class="ticket-meta">{{supportTime(ticket.created_at)}}</p><p class="ticket-body">{{ticket.body}}</p><a v-if="ticket.file" :href="ticket.file.url" target="_blank" rel="noopener">{{ $t('View attachment') }}: {{ticket.file.name}}</a></article>
<article v-for="e in ticket.entries" :key="e.id" class="ticket-card"><h2>{{ $t(e.kind==='reply'?'Support reply':e.kind==='customer_reply'?'Your follow-up':'Status update') }}</h2><p class="ticket-meta">{{supportTime(e.created_at)}}</p><p v-if="e.body" class="ticket-body">{{e.body}}</p><p v-if="e.status">{{ $t(statuses[e.status]) }}</p><a v-if="e.file" :href="e.file.url" target="_blank" rel="noopener">{{ $t('View attachment') }}: {{e.file.name}}</a></article>
<section class="ticket-card"><p v-for="(error,key) in $page.props.errors" :key="key" role="alert" class="text-red-600">{{error}}</p><button v-if="$page.props.errors.revision" type="button" @click="$inertia.reload()">{{ $t('Refresh ticket') }}</button>
<form v-if="ticket.status!=='closed'" @submit.prevent="submit('reply')"><label for="ticket-reply">{{ $t('Add a follow-up') }}</label><textarea id="ticket-reply" v-model="form.body" maxlength="5000" rows="5" required></textarea><private-attachment v-model="form.file_id" :disabled="sending" @busy="uploading=$event"/><div class="ticket-actions"><button type="submit" :disabled="sending||uploading">{{ $t('Send reply') }}</button><button type="button" @click="submit('close')" :disabled="sending||uploading||!!form.body||!!form.file_id">{{ $t('Mark resolved') }}</button></div></form>
<button v-else @click="submit('reopen')" :disabled="sending">{{ $t('Reopen ticket') }}</button></section>
</ticket-layout></template>
<script>
import {supportTime} from '@/Functions/SupportTime';

import TicketLayout from '@/Components/Support/TicketLayout';import PrivateAttachment from '@/Components/Support/PrivateAttachment';
export default{components:{TicketLayout,PrivateAttachment},props:{ticket:Object,success:String},data(){return{sending:false,uploading:false,form:{body:'',file_id:null,request_key:crypto.randomUUID()},statuses:{new:'Awaiting support',replied:'Support replied',closed:'Resolved'}}},methods:{supportTime,submit(action){if(this.sending||this.uploading)return;this.sending=true;this.$inertia.post(this.route('support.tickets.update',this.ticket.id),{...this.form,action,revision:this.ticket.revision},{preserveScroll:true,onFinish:()=>this.sending=false,onSuccess:()=>this.form={body:'',file_id:null,request_key:crypto.randomUUID()}})}}};
</script>
